### ISSUE TITLE
Can I flash WiFi ssid and pw into default NVS? (ESPTOOL-907)

### ISSUE THREAD

**Issue by hyansuper** [espressif/esptool#1001]

**Comment by dobairoland** [comment]
You can flash anything (even random bytes) to anywhere in the flash. But you  (or the the upper application layer of ESP-IDF) have to know what goes and to where. Please consult the ESP-IDF documentation to find more about this. Esptool directly cannot help you with this. And we, esptool developers, are not able to answer this question.

**Comment by dobairoland** [comment]
This is probably a good starting point: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_flash.html
