### ISSUE TITLE
pip install esptool -U --prefer-binary installs 4.8.0 (ESPTOOL-929)

### ISSUE THREAD

**Issue by matthuisman** [espressif/esptool#1014]
`pip install esptool -U --prefer-binary`
will install the "buggy" 4.8.0 whl as I suspected in comment https://github.com/espressif/esptool/pull/1011#issuecomment-2369088764

I'd recommend trying to remove that old whl (https://pypi.org/project/esptool/4.8.0/#files)
If thats not possible, then yanking / marking as broken the 4.8.0 alltogether

It will save users like me needing to blacklist the 4.8.0 as our automation uses --prefer-binary
pip install esptool!=4.8.0 -U --prefer-binary  correctly installs 4.8.1

### Operating System

Windows

### Esptool Version

4.8.0

### Python Version

3.10

**Comment by matthuisman** [comment]
fyi @radimkarnis  :)

**Comment by radimkarnis** [comment]
@matthuisman we will look into it, thank you!

**Comment by radimkarnis** [comment]
v4.8.0 wheel deleted. Thanks again for your help!

**Comment by matthuisman** [comment]
thats great :) Thank you
