### ISSUE TITLE
return in finally swallows exceptions (ESPTOOL-948)

### ISSUE THREAD

**Issue by iritkatriel** [espressif/esptool#1025]
### Operating System

NA

### Esptool Version

master branch

### Python Version

NA

### Full Esptool Command Line that Was Run

NA

### Esptool Output

```shell
NA
```

### What is the Expected Behaviour?

Avoid return in finally.

### More Information

In https://github.com/espressif/esptool/blob/8298cdcc68a8063df1ca932d42e21555e15269b3/esptool/cmds.py#L158 there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if an unhandled exception (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, or any exception is raised from an `except:` clause, it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by Honza0297** [comment]
Hello @iritkatriel and thank you for reporting this!  
We will look into this and fix it.
