### ISSUE TITLE
Unable to use esptool.py chances are I havent installed correctly or set the $PATH as I havent understood 100% (ESPTOOL-960)

### ISSUE THREAD

**Issue by ylnest2018** [espressif/esptool#1033]
### Operating System

macOS 14.2.1

### Esptool Version

4.8.1

### Python Version

Python 2.7.18 & 3.9

### Chip Description

ESP32-DEV

### Device Description

I dont think I have installed Python correcly I have used the install commands listed on this repo but for some reason when I run python -V it shows 2.7.18, when I have 3.9 installed to my /Users/<myuser>/Library/Python/3.9/

### How is Esptool Run

macOS Terminal

### Full Esptool Command Line that Was Run

esptool.py -p COM3 -b 460800 read_flash 0 ALL flash_contents.bin

### Esptool Output

```shell
zsh: command not found: esptool.py

WARNING: The scripts pip, pip3 and pip3.9 are installed in '/Users/leo/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

WARNING: The scripts activate-global-python-argcomplete, python-argcomplete-check-easy-install-script and register-python-argcomplete are installed in '/Users/leo/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

### More Information

If I run your command to upgrade python3 and pip I get:

WARNING: The scripts pip, pip3 and pip3.9 are installed in '/Users/leo/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

or

WARNING: The scripts activate-global-python-argcomplete, python-argcomplete-check-easy-install-script and register-python-argcomplete are installed in '/Users/leo/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

If I try check esptool.py version I get this:

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by dobairoland** [comment]
Hi @ylnest2018,

you can use your desired Python directly by specifying the path to it, e.g. `/Users/leo/Library/Python/3.9/bin/python -m pip install esptool`.

If you want to make `/Users/leo/Library/Python/3.9` your default python, so `python`, `pip` and similar would work without specifying the whole path then please search the Internet for "how to make a custom Python to be default on MacOS" or similar terms.

I'm closing this because it is not an esptool or its installation issue.
