### ISSUE TITLE
`write_flash -fm dio` doesn't exit after flashing

### ISSUE THREAD

**Issue by projectgus** [espressif/esptool#104]
Because of the workaround for dual-I/O flash, esptool.py doesn't exit bootloader mode after writing in dual I/O mode.

**Comment by mcauser** [comment]
I noticed this too on a WeMos D1 mini

**Comment by projectgus** [comment]
This is fixed as part of the new reset behaviour in esptool.py v2.0 (`--after soft_reset` should also work with --mode dio on esptool v2.0)
