### ISSUE TITLE
esptool v2.0 read_mac fails on esp8266

### ISSUE THREAD

**Issue by aircable** [espressif/esptool#148]
the new version 2.0-dev does not work with the ESP8266, but does on the ESP32.
the version 1.3dev works on ESP8266 but not on the ESP32.
This bug should be easy to fix, eh?

$ python esptool32.py -p /dev/tty.SLAB_USBtoUART63 read_mac
esptool.py v2.0-dev
Connecting...
Detecting chip type... ESP8266
Uploading stub...
Running stub...
Stub running...
(24, 254, 52, 155, 167, 200)
Traceback (most recent call last):
File "esptool32.py", line 2061, in 
main()
File "esptool32.py", line 1903, in main
operation_func(esp, args)
File "esptool32.py", line 1600, in read_mac
print_mac("WiFi MAC", mac[0])
File "esptool32.py", line 1595, in print_mac
print '%s: %s' % (label, ':'.join(map(lambda x: '%02x' % x, mac)))
TypeError: argument 2 to map() must support iteration

$ python esptool.py -p /dev/tty.SLAB_USBtoUART63 read_mac
esptool.py v1.3-dev
Connecting...
MAC: 18:fe:34:9b:a7:c8

**Comment by projectgus** [comment]
Thanks. Most functions should be compatible (there's an automated test suite in v2.0 that runs against esp8266 & esp32), but it obviously doesn't test read_mac! Will fix ASAP.
