### ISSUE TITLE
timeout error on master (then command completes)

### ISSUE THREAD

**Issue by sarnold** [espressif/esptool#155]
At least as far as query commands, I just got it so I don't have anything to flash it with yet...  It looks clean with 1.2.1 but master always returns a timeout error before retrying and giving the result:

```$ esptool.py --port /dev/ttyUSB1  chip_id
esptool.py v1.3-dev
Connecting...
Couldn't connect. [<class '__main__.FatalError'>; Timed out waiting for packet header]. Retrying...
Chip ID: 0x00c6ddf1
```

**Comment by sarnold** [comment]
Like I said, 1.2.1 looks fine:

```$ esptool.py --port /dev/ttyUSB1 flash_id
esptool.py v1.2.1
Connecting...
Manufacturer: ef
Device: 4016
```

**Comment by projectgus** [comment]
Thanks for reminding me about this, printing these interim errors was added in #127 and I meant to do something about it as it's a bit confusing. The previous versions are also seeing a timeout and then retrying, but they don't print anything.

**Comment by sarnold** [comment]
NonFatalError?  ;)
