### ISSUE TITLE
No version 1.3 on pypi

### ISSUE THREAD

**Issue by aaronshim** [espressif/esptool#163]
Unlike stated in the readme, doing
```
pip install esptool
```
will result in
```
RuntimeError: esptool.py only supports Python 2.x
```
because the version on pypi is 1.2.1, not 1.3.

I'm running Python 3.5.2 installed on Windows 10 using Anaconda 4.2.0

**Comment by michal037** [comment]
Try to run esptool under Python version 2.x. Python 2.x and 3.5.2 versions aren't compatible.

**Comment by aaronshim** [comment]
Dear @michal037
Thank you for your response! Yes, that is certainly a solution to get the tool to run, but it does not address the bug I intended to file, which is the inconsistency of the information on the README.

In order to fix this problem, I see one of two solutions that can be implemented.
1. Get version 1.3 on PyPi
2. Change the text of the README to make it clear that the PyPi install method will not work for Python 3.5 yet

Which one of these seems more amenable?

**Comment by projectgus** [comment]
Thanks for pointing this out. Plan was to release v1.3 soon after merging to master, but this got delayed. Will aim to release very soon, otherwise will update README until v1.3 release happens.

**Comment by projectgus** [comment]
esptool v1.3 is now released, and on pypi https://github.com/espressif/esptool/releases/tag/v1.3
