### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Endothelium** [espressif/esptool#166]
Hello,

I am trying to flash my arduino WIFI ( this model :  [Arduino Wifi](http://www.arduino.org/products/boards/arduino-uno-wifi) ).

I am on Windows and my python version is 2.7.

I downloaded epstool using pip, then i run the following command : 

`python esptool.py -p COM3 -b 9600 write_flash -ff 80m -fm qio -fs 32m 0x00000 boot_v1.4.bin_rep 0x1000 user1.bin 0x3FC000 esp_init_data_default.bin_rep 0x3FE000 blank.bin`

This is the ouput : 

```
esptool.py v1.2.1
Connecting...
Running Cesanta flasher stub...
Traceback (most recent call last):
  File "esptool.py", line 1271, in <module>
    main()
  File "esptool.py", line 1182, in main
    operation_func(esp, args)
  File "esptool.py", line 864, in write_flash
    if address == 0 and image[0] == '\xe9':
IndexError: string index out of range
```

I used this tutorial [Tutorial](http://www.arduino.org/learning/tutorials/advanced-guides/how-to-change-the-firmware-on-an-arduino-uno-wifi)

So it seems image[] is undefined but can't figure why.
I try since yesterday but i have no idea how to solve the problem.

Thanks

`

**Comment by projectgus** [comment]
Hi @Endothelium,

The error implies that one of the files you are flashing has length 0. Probably "boot_v1.4.bin_rep". Can you verify the file lengths?

(This is still a bug, esptool shouldn't crash when if a file has length 0.)

Angus
