### ISSUE TITLE
Split esptool.py into espserial.py and espimage.py (ESPTOOL-156)

### ISSUE THREAD

**Issue by projectgus** [espressif/esptool#169]
At the next major release (v3.0), some time in the future, I'd like to split the (now quite large) esptool.py source file into:

* espserial.py - All esptool commands which require a serial port connection (write_flash, read_flash, etc.)
* espimage.py - All esptool commands which work with image files, offline (elf2image, image_info, etc.)

A wrapper esptool.py command could be provided for backwards compatibility, at least for the initial release.

This may also provide an opportunity to standardise some of the command line arguments.

The disadvantage is that it will no longer be possible to copy just one file (esptool.py) and run it standalone. However it is hoped `espserial.py` and `espimage.py` could be used as standalone tools.

Now that esptool is available in pypi and on Python 3, I think there are less cases where it's necessary to just copy the script by itself into a directory to run it standalone.

If you use `esptool.py` now and you have any thoughts on whether this would make it easier or harder for your use case, please comment.

**Comment by radimkarnis** [comment]
After refactoring `esptool.py` into multiple source files, we've decided we won't be splitting it into separate tools. 

Closing this. If anyone has any thoughts about this or thinks we should reconsider this, feel free to reopen!
