### ISSUE TITLE
A fatal error occurred: Timed out waiting for packet header when using 4MB   bin file

### ISSUE THREAD

**Issue by SmartArduino** [espressif/esptool#183]
esptool.py  --port COM77 -b 921600  write
_flash --flash_freq 40m --flash_mode dio --flash_size 4MB 0x0000  t.bin
esptool.py v2.0-beta2
Connecting....
Detecting chip type... ESP8266
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Attaching SPI flash...
Configuring flash size...
Flash params set to 0x0240
Compressed 4178048 bytes to 231980...
Writing at 0x00038000... (100 %)
A fatal error occurred: Timed out waiting for packet header

**Comment by projectgus** [comment]
Thanks for reporting this. It seems like the timeout is not long enough for very large compressible files, where the ESP does a long decompression operation on the remote side. I'm able to reproduce by generating an all-zeroes file of 2MB or larger.

In the case of the file you are flashing, I'm guessing most of the data is at the beginning and then the very end, with a gap in the middle of a repeating byte or pattern? 

Will work on a fix for this, but I expect you can work around the issue for now by adding `-u` (for uncompressed flashing) to the write_flash arguments (ie `write_flash -u --flash_freq , etc`). This will be slower, but it will flash successfully.

**Comment by SmartArduino** [comment]
Thanks for u advice.
Mof the data is at the beginning and then the very end, with a gap in the middle of a repeating byte  in the file bin.
The bin may be download from the attached file:

[t.zip](https://github.com/espressif/esptool/files/820033/t.zip)

**Comment by SmartArduino** [comment]
I change 
the self._port.timeout = 100

That is ok for 4M bin.

**Comment by projectgus** [comment]
Thanks. Glad this fixed the problem. In most cases esptool.py wants a shorter timeout than this (so you don't have to wait 25 seconds to find out something has gone wrong), so the long term fix will probably be detecting how much uncompressed data was sent in each block, and adjusting the timeout to match (more uncompressed data = longer timeout.)
