### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by bubba198** [espressif/esptool#185]
Traceback (most recent call last):
  File "C:\Soft\nodemcu-pyflasher-master\esptool.py", line 28, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

**Comment by bubba198** [comment]
So sorry I wish there was a way to delete a stupid stuff like the issue I just posted. My bad

**Comment by projectgus** [comment]
No problems, happens to everyone sometimes. :)

**Comment by MHTaval** [comment]
how did you solve that. I have this problem now
