### ISSUE TITLE
i can not receive RTS  info

### ISSUE THREAD

**Issue by ouki-wang** [espressif/esptool#190]
I used a standard USB CDC device（stm32）
when i close the serial，i receive the RTS info
21 22 02 00 00 00 00 00

but when I use esptool.exe，I can not receive 21 22 02 00 00 00 00 00 to control RTS pin

**Comment by ouki-wang** [comment]
can you enable RTS control？

**Comment by ouki-wang** [comment]
will esptool.exe source code be opened?

**Comment by projectgus** [comment]
What esptool.exe are you referring to?

**Comment by ouki-wang** [comment]
@projectgus run get.exe. I can get a esptool.exe

**Comment by ouki-wang** [comment]
I have found a project source https://github.com/igrr/esptool-ck
Is is an official release version?

**Comment by projectgus** [comment]
I'm sorry but I don't understand the problem you are having at all, I need more details.

* Are you using Arduino for ESP32 to install esptool.exe?
* What device is connected to the STM32 CDC firmware?
* Where does the CDC firmware source code from?
* What host OS are you on?
* Can you post the output from a failed flash with esptool?

**Comment by projectgus** [comment]
Closing due  to a lack of information to follow up, but feel free to reopen if you have more information.
