### ISSUE TITLE
Display ESP32 silicon revision/model information

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esptool#206]
@projectgus 
angus sry for the request in Issues,
but **i have the issues**, that i can not read from command line the slicon rev id :)
can you support this "future"?

i know, we need to use extra pins for clk and cs
but i ask 👍 is it possible over esptool to check, there is psram installed and..
can we read perhabs the ID from the ESP-PSRAM32 ic?
officialy [esp-psram32 datasheet](http://espressif.com/sites/default/files/documentation/esp-psram32_datasheet_en.pdf) since june 5 is here

this can be possible like the read of flash ic - 
not sure is possible to trigger cs/clk of psram over the ROM bootloader so
that the psram returns ID...

you have the details in your hand and "head" :)
would be nice, if we can check basic things over esptool directly.
thanks!

best wishes
rudi ;-)

ps: where i can get one badge - i can not visit the camp this year.

**Comment by projectgus** [comment]
> but i have the issues, that i can not read from command line the slicon rev id :)
> can you support this "future"?

This is actually possible now, although only the numeric efuse values are displayed. We will add a feature to make this information more user-friendly.

The command you can use now is `espefuse.py -p PORT summary`. The output has a lot of information, but if you look down in the list there are two efuses CHIP_VERSION and CHIP_PACKAGE:

ESP32-D0WDQ6 silicon revision 0:
```
CHIP_VERSION           Chip version                                      = 0 R/W (0x0)
CHIP_PACKAGE           Chip package identifier                           = 0 R/W (0x0)
```

ESP32-D0WDQ6 silicon revision 1:
```
CHIP_VERSION           Chip version                                      = 8 R/W (0x8)
CHIP_PACKAGE           Chip package identifier                           = 0 R/W (0x0)
```

ESP32-D2WD silicon revision 0:
```
CHIP_VERSION           Chip version                                      = 0 R/W (0x0)
CHIP_PACKAGE           Chip package identifier                           = 2 R/W (0x2)
```

> can we read perhabs the ID from the ESP-PSRAM32 ic?

I'm going to open a second issue for this, as it's a separate (bigger) task.
