### ISSUE TITLE
Blinky example does not work on ESP-12

### ISSUE THREAD

**Issue by Navis-Raven** [espressif/esptool#219]
The blinky example does not work on ESP-12 with esptool by doing the simple 
make flash command or even by doing this esptool command : 

esptool.py -p /dev/ttyUSB0 write_flash 0x00000 blinky-0x00000.bin 0x10000 blinky-0x10000.bin

This topic is the continuty of this one https://github.com/pfalcon/esp-open-sdk/issues/279 . But I put it here because it seems there is a problem with esptool configuring with some kind of ESP-12F or/and ESP-12E .

**Comment by Navis-Raven** [comment]
PS: I'm talking about this blinky example available here, not another one: https://github.com/pfalcon/esp-open-sdk/tree/master/examples

**Comment by projectgus** [comment]
Hi @Navis-Raven ,

Sorry for the slow reply. Looking at the parent issue, it looks like you've since got this working OK. Please reopen if you think there is something esptool can do differently here.

Angus
