### ISSUE TITLE
Is there a factory "Bootloader"?

### ISSUE THREAD

**Issue by RicardoDanielSimoes** [espressif/esptool#221]
We've updated our ESP32-DevKitC with the newest Micropython Firmware. It works, but for comparison we want to undo that and reupload it to the standard Firmware. How does one go about that? I havent found anything in that direction.

**Comment by projectgus** [comment]
Hi @RicardoDanielSimoes,

The ESP32 has a bootloader in ROM, which can't be replaced or updated. This bootloader loads a second software bootloader from flash which then boots the app.

The bootloader is compiled as part of the firmware you run on the device. So if you use ESP-IDF then there is a bootloader compiled as part of IDF, Arduino for ESP32 has its own version of this bootloader, and Micropython also compiles a version of this bootloader. So reflashing from any of these environments (or any other ESP32 environment) should replace the bootloader as part of the flash.

There isn't really a "standard firmware" in this sense, just a variety of different options for running code on the ESP32. You should be able to switch between all of them interchangeably.

I'm going to close this issue as it doesn't require any changes in esptool. If you have further questions then the http://esp32.com/ is a great place to post them.

Cheers,

Angus
