### ISSUE TITLE
ESP8285 isn't correctly detected

### ISSUE THREAD

**Issue by marcelstoer** [espressif/esptool#223]
I've had this [cute ESP8285 board from Tindie](https://www.tindie.com/products/onehorse/esp8285-development-board/) for more than a year. From time to time I use it for testing stuff.

The current esptool.py fails to detect the chip type on this board properly.

> Detecting chip type... ESP8266

I don't have other ESP8285 boards like e.g. the WeMos D1 mini Lite for comparison.

**Comment by projectgus** [comment]
That's a good point. "Chip type" for now is ESP8266/ESP32 only, it's more the "device family" than the specific model number.

I'll see what we can do to detect ESP8285 specifically.

Does it work properly apart from mis-detecting it as an ESP8266?

**Comment by marcelstoer** [comment]
Yep, has worked just fine for as long as I had this chip. ESP8285 requires `dout`, though.

**Comment by marcelstoer** [comment]
I finally got around to verifying the fix - all good.

**Comment by projectgus** [comment]
@marcelstoer Good to hear. Sorry I forgot to ping you about the v2.2 release.

**Comment by marcelstoer** [comment]
No worries, I've kept coming back here to check every other week or so 😉
