### ISSUE TITLE
Unable to finish firmware upload.

### ISSUE THREAD

**Issue by Ryojikn** [espressif/esptool#225]
I'm trying to upload the firmware for an ESP-12F module, but it doesn't seems to be working.

![image](https://user-images.githubusercontent.com/4712257/29483149-b3d241c2-8476-11e7-884b-a71209369e1e.png)

![image](https://user-images.githubusercontent.com/4712257/29483153-bfb45be2-8476-11e7-9360-c287eba7e405.png)

For all the places that I've consulted, everything seems to be ok, i'm using both flash download tool 3.4 and 2.4, and the SDK is the latest version available here: http://espressif.com/en/support/download/sdks-demos?keys=&field_type_tid%5B%5D=14

Still, I'm having the error message that I'm presenting above.
Can anyone help me? I have two modules, both of them are not responding to AT commands, I've tried to flash firmware into them a couple times, and now I'm kinda lost.

**Comment by projectgus** [comment]
Hi @Ryojikn ,

This is the github repository for esptool.py, the Python-based command line tool for flashing ESP8266 and ESP32.

For questions about the GUI flash download tool, please post on the Espressif BBS: http://bbs.espressif.com/

You may want to try installing esptool.py and flashing from the command line to see if you get a different result.

Sorry I can't be of more assistance,

Angus
