### ISSUE TITLE
Digest mismatch when doing read_flash

### ISSUE THREAD

**Issue by plerup** [espressif/esptool#234]
Hi,

I always get the "Digest mismatch" error when using read_flash. This is regardless if the whole flash or just a part is dumped.

I tried the old version 1.3 and here it works flawlessly

This is for esp8266

**Comment by projectgus** [comment]
Hi @plerup ,

Can you please post the full esptool.py command line you're using? If they're publically shreable, could you please also attach the .bin files you are flashing?

Angus

**Comment by plerup** [comment]
Hi,

Seems like there was something wrong with my FTDI-chip

Sorry about this :blush: 

BR
/Peter

**Comment by projectgus** [comment]
No problems, glad you got it figured out.
