### ISSUE TITLE
Document using RFC2217 to talk to Espressif devices via network serial link

### ISSUE THREAD

**Issue by me21** [espressif/esptool#238]
Please add option to use other devices (TCP port, FIFO file on Linux or pipe on Windows) to talk to Espressif chips. This will make it possible to flash ESP remotely by using some intermediate program that will forward the commands to real ESP port.

I think it will be impossible to set baud rate and to control DTR/RTS in that case, but it will be a well-known limitation, so that user will make necessary actions himself (i.e. reboot ESP to bootloader beforehand).

**Comment by me21** [comment]
Although something similar can be implemented using https://freevirtualserialports.com/ (it can create virtual serial port connected to named pipe), but it requires another piece of software to be installed.

But it can be used as temporary workaround.

**Comment by me21** [comment]
Although something similar can be implemented using https://freevirtualserialports.com/ (it can create virtual serial port connected to named pipe), but it requires another piece of software to be installed.

But it can be used as temporary workaround.

**Comment by projectgus** [comment]
This functionally should be possible now but it's not documented as I haven't thoroughly tested it.

The pyserial library which esptool is built on supports RFC2217, which is a standards-compliant way to tunnel serial port traffic over a TCP telnet session. [Docs here](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#rfc-2217-network-ports). If you use the form mentioned there as the port name when running esptool.py (`rfc2217://host:port`) then it should work, including flow control if DTR & RTS are hooked up at the other end.

Looks like you're on Windows. A quick search for "rfc2217 Windows" shows there are quite a few free options for serial servers on this platform.

pyserial also includes a simple RFC2217 server example:
https://github.com/pyserial/pyserial/blob/master/examples/rfc2217_server.py

Please let us know how you get on with this.

Angus

**Comment by projectgus** [comment]
@me21 did you have any luck with this?

**Comment by me21** [comment]
I haven't tested yet, but when I have, I'll let you know.

**Comment by projectgus** [comment]
Thanks for the update @me21, no problems. I'm happy to leave this issue open until we have an officially documented way to use RFC2217.

**Comment by me21** [comment]
Now I can confirm it works with RFC2217 ports with small PR #251.

**Comment by projectgus** [comment]
Fantastic, thanks for confirming this @me21

**Comment by projectgus** [comment]
Now documented (with some simple examples) at https://github.com/espressif/esptool/wiki/Remote-Serial-Ports
