### ISSUE TITLE
Document erasing a flash block range

### ISSUE THREAD

**Issue by OtherCrashOverride** [espressif/esptool#266]
esptool currently can read and write flash, but it can not erase it.  During development it is desirable to erase a range of flash instead of the entire flash.

**Comment by projectgus** [comment]
This is actually possible now, although it doesn't appear to be documented in the README so that should be fixed:

```
$ esptool.py erase_region --help
usage: esptool erase_region [-h] [--spi-connection SPI_CONNECTION]
                            address size
```
