### ISSUE TITLE
Support setting active OTA partition on ESP32

### ISSUE THREAD

**Issue by OtherCrashOverride** [espressif/esptool#267]
During development, it desirable to change the active OTA partition for testing.  Esptool should provide a command to choose the factory or OTAn partition as active.

**Comment by projectgus** [comment]
I agree this is a desirable feature, but it will be added to ESP-IDF not esptool.py. There's nothing software-specific about esptool.py, it's a hardware level tool. The ota_data partition (and the partition table concept underlying it) are an ESP-IDF software feature.

We can still add this functionality to a command line tool so it's easy to integrate IDF partition operations into other software environments.

Please consider opening this as a feature request on the ESP-IDF repository.
