### ISSUE TITLE
Support for ESP-WROOM-32 with Display ? ESP32 ROM does not support function read_flash.

### ISSUE THREAD

**Issue by ds2k5** [espressif/esptool#268]
Hello,
have esptool v 2.1 and a ESP-WROOM-32 with Display.
But the esptool say:

# esptool --chip esp32 --port /dev/ttyUSB0 --baud 115200 read_flash 0x000 4194304 esp-WROOM-32_backup.bin
esptool.py v2.1
Connecting........__
Chip is ESP32D0WDQ6 (revision 1)
Enabling default SPI flash mode...

A fatal error occurred: ESP32 ROM does not support function read_flash.

# lsusb

Bus 001 Device 004: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light

# esptool chip_id
esptool.py v2.1
Connecting........_
Detecting chip type... ESP32
Chip is ESP32D0WDQ6 (revision 1)
Enabling default SPI flash mode...
Chip ID: 0x2430aea40ecf
Hard resetting...

How to fix this ?

Thanks

**Comment by ds2k5** [comment]
Solution:  pip3 install --upgrade esptool

run esptool.py insted esptool

esptool.py v2.2.1 looks like it work

**Comment by projectgus** [comment]
I'm not sure why the original command didn't work, but I'm glad you found a method which does.
