### ISSUE TITLE
Minor: For trace, show all data as hex codes

### ISSUE THREAD

**Issue by nkolban** [espressif/esptool#286]
When we switch on trace for esptool (and THANK YOU for that option), we get hex dumps which, to me, are useful.  However the hex dumps only dump hex for non-printable characters.  For printable characters, they show as ... well ... their ASCII representations.  Here is an example:

```
Z\xa5\xf8\xff-\n2\xa0\xc5\xa0#\x93\x1d\xf0\x00,
```

From the above, what we see is a "mish-mash" of characters and hex codes.  This issue (very minor) asks for the consideration of better formatting for the dumps.  Specifically, I would love to see the dumps exclusively in hex.  For extra credit, a 16 byte hex dump with a column on the right showing the ASCII version would be ideal ... similar to:

https://i.stack.imgur.com/uwgeO.png
![image](https://user-images.githubusercontent.com/3421732/37880824-e353f4c0-3053-11e8-96a7-9444ef71653a.png)

**Comment by projectgus** [comment]
For the benefit of anyone reading this, there's a workaround to convert to hex documented on the wiki page:
https://github.com/espressif/esptool/wiki/Serial-Protocol#tracing-esptoolpy-serial-communications

But I agree this would be a good feature to have in the dump output.
