### ISSUE TITLE
Docs: Clarification on the response Size field

### ISSUE THREAD

**Issue by nkolban** [espressif/esptool#288]
In the documentation on the Wiki found here:

https://github.com/espressif/esptool/wiki/Serial-Protocol#response

We find that the Size field is 2 bytes but the documentation states

"Size of data field. At least 2 bytes (ESP8266) or 4 bytes (ESP32)."

My experimentation seems to be showing (at least so far) that the size *size* for an ESP32 remains at 2 bytes (16 bits).   This issue asks for clarification.  Is the field 2 bytes or 4 bytes on an ESP32?  If it is 4 bytes, why might I be seeing instances of 2 byte sizes?

**Comment by projectgus** [comment]
Hi @nkolban,

Thanks for pointing this out. I've updated the wiki Response section to explain the difference:
https://github.com/espressif/esptool/wiki/Serial-Protocol#response

(Short version: status bytes are always two bytes when the software stub loader is running, only the ESP32 ROM sends 4 bytes of status.)
