### ISSUE TITLE
Clobbering of flash contents when write address and/or size is not a multiple of 4k chunks. (ESPTOOL-147)

### ISSUE THREAD

**Issue by Spanguole** [espressif/esptool#306]
# Bug Description
When using the `write_flash` function to an address that is not a multiple of 4k (e.g. writing to `0x2588`) and/or with data which has a size that is not a multiple of 4k (e.g. 256 bytes), all the multiple-of-4k chunks that had any amount of data written end up with data being clobbered to `0xff` in the regions that were NOT written to.

Example: running `esptool.py write_flash 0x3360 0x80 smallchunk.bin` will set all the bytes that were not touched in the `0x3000-0x4000` region to `0xff`, while the 128 bytes that were written will be fine.

* Operating system: GNU/Linux
* Python version: Python 3.4.6
* ESP hardware in use: Esp-8266 on a Wemos D1 Mini

# What is the expected behaviour?
What expected is that any data not explicitly touched by the write operation to be retained OR at least a diagnostic warning about data being clobbered should be issued.

**Comment by mkirisame** [comment]
This still needs fixing.
