### ISSUE TITLE
Explain boot log messages in wiki

### ISSUE THREAD

**Issue by marcelstoer** [espressif/esptool#308]
https://github.com/espressif/esptool/wiki/ESP8266-Boot-ROM-Log is fairly naked without any explanations. How about adding the explanations from Espressif at https://bbs.espressif.com/viewtopic.php?t=896? That post mentions an official documentation but I failed to find it.

**Comment by projectgus** [comment]
I know this wasn't your request, but I've added equivalent explanations for ESP32 here:
https://github.com/espressif/esptool/wiki/ESP32-Boot-Mode-Selection#boot-mode-message

ESP8266 will be coming soon. :)

**Comment by marcelstoer** [comment]
Any chance we can get this as a Christmas present 🎄?

**Comment by projectgus** [comment]
Looks like @AABatteries added this information to the wiki in January. Thanks, @AABatteries! :)
