### ISSUE TITLE
Serial port not closed explicitly in main()

### ISSUE THREAD

**Issue by cefn** [espressif/esptool#313]
(Please delete any lines which don't apply.)

* Operating system:

All, but particularly affects Windows because of the implementation of pyserial.

* Python version: (`python -V` to check this)

All

* ESP hardware in use:

All, but demonstrated with NodeMCU-M ESP8285 running over CH340

# Full esptool.py command line as run:

```python
import sys
import esptool

sys.argv = "esptool.py --after hard_reset --port COM3 flash_id".split()
esptool.main()
sys.argv = "esptool.py --after hard_reset --port COM3 erase_flash".split()
esptool.main()
sys.argv = "esptool.py --after hard_reset --port COM3 --baud 1500000 write_flash --flash_mode dout --flash_size 1MB 0 C:\\Users\\cefn\\Desktop\\vgkits-vanguard\\vgkits\\vanguard\\data\\firmware\\vanguard-0.1.0.bin".split()
esptool.main()
```

# Full output from esptool.py (please copy and paste all lines of output)

> (venv) C:\Users\cefn\Desktop\vgkits-vanguard>python trytool.py                                                          esptool.py v2.3.1                                                                                                       Connecting....                                                                                                          Detecting chip type... ESP8266                                                                                          Chip is ESP8285                                                                                                         Features: WiFi, Embedded Flash                                                                                          Uploading stub...                                                                                                       Running stub...                                                                                                         Stub running...                                                                                                         Manufacturer: 51                                                                                                        Device: 4014                                                                                                            Detected flash size: 1MB                                                                                                Hard resetting via RTS pin...                                                                                           esptool.py v2.3.1                                                                                                       Traceback (most recent call last):                                                                                        File "trytool.py", line 7, in <module>                                                                                    esptool.main()                                                                                                        File "C:\Users\cefn\Desktop\vgkits-vanguard\venv\lib\site-packages\esptool.py", line 2349, in main                        esp = ESPLoader.detect_chip(args.port, initial_baud, args.before, args.trace)                                         File "C:\Users\cefn\Desktop\vgkits-vanguard\venv\lib\site-packages\esptool.py", line 222, in detect_chip                  detect_port = ESPLoader(port, baud, trace_enabled=trace_enabled)                                                      File "C:\Users\cefn\Desktop\vgkits-vanguard\venv\lib\site-packages\esptool.py", line 193, in __init__                     self._port = serial.serial_for_url(port)                                                                              File "C:\Users\cefn\Desktop\vgkits-vanguard\venv\lib\site-packages\serial\__init__.py", line 88, in serial_for_url        instance.open()                                                                                                       File "C:\Users\cefn\Desktop\vgkits-vanguard\venv\lib\site-packages\serial\serialwin32.py", line 62, in open               raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))                     serial.serialutil.SerialException: could not open port 'COM3': PermissionError(13, 'Access is denied.', None, 5)  

# What is the expected behaviour?

Ideally any valid sequence of calls to main will succeed.

# Do you have any other information from investigating this?

I have a fix and a pull request coming your way

# Is there any other information you can think of which will help us reproduce this problem?

The permissions issue comes when running on Windows 10, but I think this is just a by-product of other OSs being a bit more forgiving of a still-open port. Probably it should be closed in all cases.

**Comment by projectgus** [comment]
Thanks @cefn . Fixed via PR in master & the v2.4.0 release.
