### ISSUE TITLE
Please help me understand how esptool sets flash size...

### ISSUE THREAD

**Issue by Cicero-MF** [espressif/esptool#315]
This probably isn't the place for this, but its my only option as nobody else can help me and I presume you guys know the internals.  
Long story, but I have ESP12's in the field running firmware compiled to 512KB (pre-OTA), and now I need to load on 4MB (32Mb) firmware and its failing due to RF cal data issues (I am aware I need to flash rf init data to certain addresses dependent on flash sizes, but even if I do so its looking at the original 512KB addresses and not my 4MB addresses).  I only have access to using the ROM loader, not the stub loader.

I've done a serial trace for:
`espflash.py --no-stub --trace --port COM6 --baud 115200 write_flash --flash_freq 40m --flash_mode qio --flash_size 1MB 0x0000 firmware/0x00000.bin 0x12000 libesphttpd/webpages.espfs 0x40000 firmware/0x40000.bin `

and 

`espflash.py --no-stub --trace --port COM6 --baud 115200 write_flash --flash_freq 40m --flash_mode qio --flash_size 8MB 0x0000 firmware/0x00000.bin 0x12000 libesphttpd/webpages.espfs 0x40000 firmware/0x40000.bin ` 

just to see the difference, and from what I can see the serial data sent is the same, even though I've specifically told it the flash size is different?  
Trawling the python code, it looks as though all those flash parameters are skipped if not using the stub.  

But then how does it ever know what its using if you change memory sizes?

**Comment by projectgus** [comment]
Hi @Cicero-MF ,

Sorry for the slow reply.

There is some info about flash options like size here:
https://github.com/espressif/esptool#flash-modes

When flashing to offset 0x0, the 8 byte header at the beginning of the image file is updated with some binary values depending on the flash size/mode/etc arguments (although the default is not to change them).

So if you flash with `--flash-size 1MB` and read back the flash, you'll see a different byte in the header near offset 0x0 compared to `--flash-size 8MB`.

If your OTA update is able to rewrite the binary at offset 0x0, you can write with `--flash-size 4MB` and then write the RF cal data as if it was a 4MB flash size.

If your OTA update is not able to rewrite the binary at offset 0x0, this header won't be changed and calibration will always look for the RF cal data as if it was a 512KB flash size.

**Comment by Cicero-MF** [comment]
Thanks for getting back to me.  Also found this: https://richard.burtons.org/2015/05/17/esp8266-boot-process/ which further explains what you're saying.

Appreciate the help.
