### ISSUE TITLE
New board for magic home?

### ISSUE THREAD

**Issue by ZoltanSzilagyiCse** [espressif/esptool#318]
Alright, I just bought a Magic Home LED controller from AliExpress and when i opened it I got this:

![Scheme](https://lh3.googleusercontent.com/2Vp2bmgjKHXxxoY3pydJzAgV6-Us1MbTrw74tBUa9sAgp69ET35yBzkz_-2BjTFBy6h1OIQtWfzGWTo1-RSWhjuWYG0CWc0cBHV704HgOM3u0a6CfcFRz6rKOlzg3WZqbmz9YxiKJg=w711-h947-no)

![Scheme](https://lh3.googleusercontent.com/o2_BuR7Jhjo2jK_s4VqljEKKA_fYHKspAzno8qv8JttBuy9RxUNSMe2xNAdKyjo_khVy9jXzQRz2z8lCDsiezgAxrAThfPT3Mr2qv64eB6bYQhQT37k653Z89cdqn_deE2j0om5BEQ=w711-h947-no)

I flashed both version (the 1.0 and the 2.0 too), then I reboot it (disconnected then connected the power) but the WiFi name never appeared. I think it's one of the cheapest version of this OR this maybe a total new board? (I already flashed 2 ESP modules before, so I did everything correctly)

**Comment by projectgus** [comment]
Hi @ZoltanSzilagyiCse ,

Sorry, I'm not sure I understand the issue with esptool here.

ESP8285 is an [Espressif WiFi MCU chip](https://www.espressif.com/en/products/hardware/socs) (first announced in 2016) and is supported by esptool.py.

> I flashed both version (the 1.0 and the 2.0 too)

I'm not sure what this means. Espressif can't provide support for a third party's hardware design using Espressif chips. You'll need to talk to whoever produces the Magic Home product or firmware to get support - or maybe reverse engineer it yourself if no support is available.

If you think that esptool.py is not flashing the ESP8285 chip correctly, please let me know and I can reopen this issue. But this sounds like a firmware problem with this particular device's firmware (maybe the firmware you flashed is not compatible with ESP8285). I'm sorry but I can't help you with this.

**Comment by coolineho** [comment]
i have the same board too, did you manage to flash this?

**Comment by ZoltanSzilagyiCse** [comment]
Yes, need to change some pinout number in the source code. It looks like the board has different layout and pinouts. Just a note: I only used the 1.0 version not the newer 2.0.

**Comment by ZoltanSzilagyiCse** [comment]
I uploaded the file here: [Google Drive](https://drive.google.com/open?id=1agCNaM6bx8TqClvsVJ2V9b8KqS6vGM00)

Just flash it or upgrade an existing one

**Comment by coolineho** [comment]
i got it to flash ;)

thanks
