### ISSUE TITLE
Is the bootloader.bin in test/images for ESP32 or ESP8266 ?

### ISSUE THREAD

**Issue by glucee** [espressif/esptool#330]
I want to reflash the bootloader to a new produced ESP8266, is the test/images/bootloader.bin the correct bootloader of that ?

**Comment by projectgus** [comment]
That is an ESP-IDF ESP32 bootloader. The `test/images/` directory contains binaries for running esptool.py tests, they are not suitable for any other purpose.

There are different flash-resident bootloaders for different ESP8266 SDK environments. Suggest looking for the bootloader which is bundled with whatever SDK you are using for your firmware.
