### ISSUE TITLE
"MD5 of file does not match data in flash!" after updating esp-idf

### ISSUE THREAD

**Issue by Th-Havy** [espressif/esptool#331]
* Operating system: Windows 10
* Python version: 2.7
* ESP hardware in use: ESP WROOM32 (devkit)

After updating the esp-idf (git pull origin master, git submodule update --init) I obtained an error on a previously working app. The error message is "A fatal error occurred: MD5 of file does not match data in flash!". The compilation is performed correctly to the end but esptools cannot flash the app into the esp32.

I tried make clean, make erase-flash (or something similar) but nothing worked. Eventually I just copy-pasted the default project files (makefiles, menuconfigs, etc...) from the hello world example which corrected the issue. I hope it can help someone.

I don't know if there is a special command to update an app that was created using a previous version but it's definitely very frustrating to loose a lot of time with an error message that is not very explicit and the documentation does not provide information on how to solve this.

**Comment by jcert** [comment]
Had the same problem, your issue saved me a lot of time, thanks.
