### ISSUE TITLE
Please include the test/ directory on PyPI

### ISSUE THREAD

**Issue by loader-bsd** [espressif/esptool#339]
Please include the test/ directory in the release tarball on PyPi.
https://pypi.org/project/esptool/

**Comment by projectgus** [comment]
Hi @loader-bsd ,

Thanks for getting in touch. I deliberately left this out because most users (rather than developers) of esptool won't need to use it, and it significantly increases the size of the package (because of all the binary images). May I ask why you need it in the package?

**Comment by radimkarnis** [comment]
I’m closing this issue because it has been inactive for a few months and it seems like it's not relevant anymore. Please reopen if further discussion is needed.
