### ISSUE TITLE
Make sure all files are closed

### ISSUE THREAD

**Issue by borro0** [espressif/esptool#340]
(Please delete any lines which don't apply.)

* Operating system: Windows 8
* Python version: (`python -V` to check this) 3.6.6
* ESP hardware in use: ESP8266

I used the esptool.py release 2.5.0

I've made very small modifications to the script so I could call it from another python script. (main takes args as arguments). I've done this so I can call it inside my python postbuild script.

When the esptool.main(args) call was finished, I could not delete the file which was used as input for the script. This was because the esptool did not close all file pointers.

I fixed this by replacing all f.open() with "with open() as f:"

And iteratively called argfile.close()

Although this is already used in most places, it was not everywhere.

**Comment by projectgus** [comment]
Hi @borro0 ,

This seems like quite a common use case for people using esptool (which is reasonable, as the other classes exposed in the esptool module don't offer the full functionality et.)

Would you be able to send a [GitHub pull request](https://help.github.com/articles/about-pull-requests/) with your modifications, please?

**Comment by borro0** [comment]
Done: #341
