### ISSUE TITLE
"read_flash" not working on Windows10

### ISSUE THREAD

**Issue by vel2000** [espressif/esptool#353]
(Please delete any lines which don't apply.)

* Operating system: Windows10/64
* Python version: 2.7
* ESP hardware in use: 8266

# Full esptool.py command line as run:
esptool.py --port COM5 -b 115200 read_flash 0 0x100000 firmware.bin
# Full output from esptool.py (please copy and paste all lines of output)
```
esptool.py v2.5.0
Serial port COM5
Connecting......
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
MAC: bc:dd:c2:ea:47:64
Uploading stub...
Running stub...
Stub running...      <---stucks here
```
# What is the expected behaviour?
read flash and save it to file "firmware.bin"
# Do you have any other information from investigating this?
same command line (except --Com 5) works on a Raspberry Pi with esptool 2.5 and flash is properly read and saved to firmware.bin
BTW: erase_flash and write_flash work on Win10 as expected.

**Comment by andrethomas** [comment]
What type of usb serial connection are you using?

My best guess is the Windows driver for the usb serial device is malfunctioning.

**Comment by projectgus** [comment]
Hi @vel2000 ,

Thanks for being patient while I got back to you. Can you please try adding the --trace argument, ie:

```
esptool.py --trace --port COM5 -b 115200 read_flash 0 0x100000 firmware.bin
```

**Comment by lev2k** [comment]
This "issue" can be closed.
After some tests I can confirm, it's a hardware/driver (no official Win10 drivers), issue under Win 10.
Same device works reliable under Windows 7.

**Comment by projectgus** [comment]
Thanks for the update, @lev2k.
