### ISSUE TITLE
Cannot connect after "Hard resetting via RTS pin..." message

### ISSUE THREAD

**Issue by geonhong** [espressif/esptool#354]
(Please delete any lines which don't apply.)

* Operating system: macOS Sierra
* Python version: (`python -V` to check this) python 2.7.13
* ESP hardware in use: ESP8266

# Full esptool.py command line as run:
I first connected the ESP8266 via FTDI and run as follows
`esptool.py -p /dev/cu.usbserial-00000000 chip_id`
and it gave me the following messages:

> [geonhong@imac esptool]$ ./esptool.py -p /dev/cu.usbserial-00000000 chip_id
> esptool.py v2.5.1-dev
> Serial port /dev/cu.usbserial-00000000
> Connecting....
> Detecting chip type... ESP8266
> Chip is ESP8266EX
> Features: WiFi
> MAC: 84:f3:eb:93:c6:53
> Uploading stub...
> Running stub...
> Stub running...
> Chip ID: 0x0093c653
> Hard resetting via RTS pin...

After I re-run the exactly the same command but it returns a connection failed error as follows:

> [geonhong@imac esptool]$ ./esptool.py -p /dev/cu.usbserial-00000000 chip_id
> esptool.py v2.5.1-dev
> Serial port /dev/cu.usbserial-00000000
> Connecting........_____....._____....._____....._____....._____....._____....._____
> 
> A fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet header

I bought 5 more esp8266 devices but all of those devices showed the same symptom.

What might be the reason and what should I do at the moment?

**Comment by projectgus** [comment]
What ESP8266 based piece of hardware are you using?

**Comment by geonhong** [comment]
Sorry for late reply and now this issue has been resolved.

1. I am using ESP8266 module, which can easily be found on the internet, such as AliExpress.
I bought one at a local web store:
https://smartstore.naver.com/ic11401/products/548797461?NaPm=ct%3Djo9hjp0z%7Cci%3Dcheckout%7Ctr%3Dppc%7Ctrx%3D%7Chk%3D6a879a99299bc7c313e14e0e0e79c500ffebd72a

2. The problem mostly regarded to the power source. 
I have been using FTDI232 for flashing an ESP8266 module and 3.3V power source from the FTDI232 was applied to the ESP8266. And it's been connected to my MacBook Pro.
I have no idea about the reason why it's been resolved after I replaced the power source, anyway, it has been resolved at the moment.

**Comment by projectgus** [comment]
Yes, FTDI chips' onboard regulators do not provide enough current to power an ESP8266. This is mentioned in the troubleshooting guide: https://github.com/espressif/esptool/#power-supply-rating

**Comment by NewtronReal** [comment]
Can we upgrade its firmware? then how?

**Comment by VeeruSubbuAmi** [comment]
This article might help you to to understand anf fix the issue
https://electronicsinnovation.com/hard-resetting-via-rts-pin-fixed-explained/

**Comment by projectgus** [comment]
@VeeruSubbuAmi This is half right, in that it's not an error. However esptool doesn't use RTS/CTS for flow control. RTS & DTR pins are used by esptool to reset the chip and control the boot mode: https://github.com/espressif/esptool/wiki/ESP8266-Boot-Mode-Selection#automatic-bootloader
