### ISSUE TITLE
Timed out waiting for packet content

### ISSUE THREAD

**Issue by Bigun** [espressif/esptool#355]
* Operating system: Ubunu and Windows 10
* Python version: 3.6
* ESP hardware in use:  ESP8266EX -> ESP-12E

I did not code this firmware, I'm just trying to write it to flash.

So, I was given a broken Mr.Robot Badge, I took up the challenge to fix it.  I finally established the original ESP-12E chip that came with the unit was faulty (was unable to establish any kind of connection with the chip).  I de-soldered the chip, and soldered the new one on, and had... more success.

I enter the chip in programming mode, then:

```
bigun@meeseeks:~/Downloads$ sudo python ./esptool-master/esptool.py write_flash 0x00000 ~/Downloads/MrRobotFirmware.bin 
esptool.py v2.5.1-dev
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
MAC: 60:01:**omitted**
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Warning: Could not auto-detect Flash size (FlashID=0xffffff, SizeID=0xff), defaulting to 4MB
Compressed 952912 bytes to 472489...

A fatal error occurred: Timed out waiting for packet content
```

After some reading, I saw you like to see the output of espefuse when this happens:

```
bigun@meeseeks:~/Downloads$ sudo python ./esptool-master/espefuse.py --port /dev/ttyUSB0 summary
espefuse.py v2.5.1-dev
Connecting....

A fatal error occurred: Timed out waiting for packet header
```

I purchased the chip from here:  https://www.amazon.com/gp/product/B01GZ0687C/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

It came with two, so I can swap chips if needed.  However, if there is a known manufacturer of reliable chips, I'm willing to purchase more.

**Comment by projectgus** [comment]
Hi @Bigun ,

ESP8266 doesn't have user-settable efuses, so it's simpler in this case.

The symptoms you have indicate that the ESP8266 can't communicate with its attached SPI flash chip. The fix may be as simple as resoldering the chip on board, or finding a short on the GPIOs which are attached to the flash chip on the board. If it's an ESP-12E module and it's previously worked then I would suggest checking the pads of the module for shorts or unexpected connections.

Or you can purchase a new ESP-12E module (Espressif don't make these, but they're available from many online electronics vendors.)

As this is not an issue with esptool itself, I'm going to close this issue.

Angus
