### ISSUE TITLE
ESP8285 ready timeout

### ISSUE THREAD

**Issue by edf15** [espressif/esptool#358]
(Please delete any lines which don't apply.)

* Operating system: Windows
* Python version: (`python -V` to check this) 2.7
* ESP hardware in use: ESP8285

# Full esptool.py command line as run:
esptool.py -p COM3 write_flash -fm dout -ff 40m -fs detect --no-compress 0x00000 "C:\Users\Inc-Ed\Dropbox (Zakat Company)\Manufacturing Test\Neutron\WiFi\ESP8266_AT_Bin_V1.6.1\SLOT1\bin\boot_v1.7.bin" 0xfc000 "C:\Users\Inc-Ed\Dropbox (Zakat Company)\Manufacturing Test\Neutron\WiFi\ESP8266_AT_Bin_V1.6.1\SLOT1\bin\esp_init_data_default_v08.bin" 0xfb000 "C:\Users\Inc-Ed\Dropbox (Zakat Company)\Manufacturing Test\Neutron\WiFi\ESP8266_AT_Bin_V1.6.1\SLOT1\bin\blank.bin" 0x01000 "C:\Users\Inc-Ed\Dropbox (Zakat Company)\Manufacturing Test\Neutron\WiFi\ESP8266_AT_Bin_V1.6.1\SLOT1\bin\at\512+512\user1.1024.new.2.bin"

# Full output from esptool.py (please copy and paste all lines of output)
esptool.py v2.5.0
Serial port COM3
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
MAC: dc:4f:22:c0:20:a9
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Flash params set to 0x0320
Wrote 16384 bytes at 0x00000000 in 1.5 seconds (90.1 kbit/s)...
Hash of data verified.
Wrote 16384 bytes at 0x000fc000 in 1.4 seconds (91.1 kbit/s)...
Hash of data verified.
Wrote 16384 bytes at 0x000fb000 in 1.4 seconds (91.1 kbit/s)...
Hash of data verified.
Wrote 409600 bytes at 0x00001000 in 36.8 seconds (89.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

# What is the expected behavior?
After programming, I turn off the ESP8285, pull gpio0 back to high, and try to turn back on the ESP8285 to scan the wifi networks around, only that I never get a "ready" or "rdy" message from the ESP82855. I don't have a problem when I use ESPFlashDownloadTool_v3.6.4. I'm trying to flash ESP8266_AT_Bin_V1.6.1. I downloaded it from https://www.espressif.com/en/support/download/at

Any help would be greatly appreciated, Thanks

**Comment by CaptainMiddle** [comment]
Hi
Try to set your flash size to 8MB. I had the same problem and it worked for me

**Comment by atoy100** [comment]
This issue can/was solved by reading the contents of the .bin files using the esptool.py from the ESPFlashDownloadTool_v3.6.4 flash, and then reflashing with those good .bin files using esptool.py.  It appears the tool changes a couple bits that esptool.py does not.

**Comment by projectgus** [comment]
Closing as it seems like this is resolved.
