### ISSUE TITLE
espefuse: Multiple commands in one execution (ESPTOOL-114)

### ISSUE THREAD

**Issue by projectgus** [espressif/esptool#360]
Feature request via esp32.com.

For example:

> espefuse.py --port COM1 burn_key flash_encryption My_encryption_key.bin  burn_efuse FLASH_CRYPT_CNT

**Comment by dobairoland** [comment]
This has been addressed with the following commits: cd44a5087bdfac1d9608031c2af049922b22231b, ecb8275c491def660e5b4a2bfbde6b9e7941b6d8, acee17d0dec2e04ea4ad6cbe7402bd816097079b, 978fa4eda07a9fd64c57ef1666656420f37dffe9.

Documentation: https://github.com/espressif/esptool/wiki/espefuse#execute-efuse-python-script
