### ISSUE TITLE
Getting improper boot messages

### ISSUE THREAD

**Issue by mimansamaheshwari** [espressif/esptool#363]
I am working on making a development board of WROOM-32. The driver chip on this board is CH340G. My problem is that whenever I press reset button I am not getting proper boot message. The boot message appears in the form displayed below:
```
ets Jun⸮⸮⸮⸮6 00:22:57

⸮.⸮⸮⸮⸮ (POWERON_RESEU⸮I⸮⸮⸮⸮0x17 (SPI_FA*⸮e1M!}	==Q⸮
confi֥⸮: 0, SPIWP:0xee
,k⸮E⸮⸮⸮0x00,q_drv:0⸮0,d_drv:0x00,cs0_dr⸮⸮⸮⸮0,hd_drv:0x00,wpE⸮⸮:0x00
mode:DIO,⸮⸮⸮k div:1
load:0x&⸮⸮⸮⸮8,len:4
load:⸮⸮fff001c,len:808
l+⸮⸮0x40078000,len:6¢j
load:0x40080000,⸮⸮⸮6696
entry 0x400⸮⸮*⸮
```
Sometimes I get proper debug message and most of the times boot message appears in the form shown above.
Any hints for the reason behind this problem?

**Comment by projectgus** [comment]
Hi @mimansamaheshwari ,

Sorry for the slow response.

It looks like the serial connection to the CH340G is corrupt or noisy. I'd suggest checking the U0TXD pin of the ESP32 with an oscilloscope. And also making sure both chips are correctly powered and well connected to a common ground.

This output is all printed by ESP32 ROM code, so there's nothing that esptool or any other software tool can do to remove the corruption.

Angus
