### ISSUE TITLE
Is there any way to Update bootloader firmware over the air ?

### ISSUE THREAD

**Issue by jegajith** [espressif/esptool#375]
We have requirement to update the secondary boot loader for one of our product. 
Experts advice required on this topic.

**Comment by projectgus** [comment]
Hi @jegajith ,

esptool is a serial flashing tool, so it can't do any kind of OTA updating.

You haven't said what chip (ESP8266 or ESP32) you are using and which software framework, but in general this is not supported - there's only copy of the bootloader, and updating the bootloader requires erasing and then re-writing it. If a power failure or a crash occurs in the middle of this process, the device will be bricked until a physical reflash (with esptool.py or similar) can be done.

If you have more questions about this, good places to post are https://esp32.com (for ESP-IDF and ESP32 Arduino) and https://bbs.espressif.com (for ESP8266 official SDKs). If you're using a different SDK, they probably have a discussion forum as well.

Angus

**Comment by jegajith** [comment]
@projectgus  Thank you for your answer
