### ISSUE TITLE
cannot erase flash memory on Nodemcu

### ISSUE THREAD

**Issue by taruntadikonda** [espressif/esptool#403]
(Please delete any lines which don't apply.)

* Operating system:windows10
* Python version: 3.7
* ESP hardware in use:Nodemcu

# Full esptool.py command line as run:

esptool.py --port COM3 erase_flash

# Full output from esptool.py (please copy and paste all lines of output)

esptool.py v2.6
Serial port COM3
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet header

# What is the expected behaviour?

# Do you have any other information from investigating this?

# Is there any other information you can think of which will help us reproduce this problem?

**Comment by projectgus** [comment]
Have you tried the Troubleshooting steps written here?
https://github.com/espressif/esptool#troubleshooting

Also, if the board you have has a "PROG" or "MODE" button. try holding it down while flashing starts.

Also, I don't know exactly what "nodemcu" is (there are dozens of boards marked "nodemcu" for both ESP8266 and ESP32), but this is probably a problem with the particular board you have. It may be faulty.

**Comment by projectgus** [comment]
Closing due to lack of update.
