### ISSUE TITLE
Connection Failure on Windows: "Timed out waiting for packet header"

### ISSUE THREAD

**Issue by StevenLawsonBAF** [espressif/esptool#425]
* Operating system: Windows 7
* Python version: Python 3.7.3
* ESP hardware in use: ESP32-WROOM-32D

# Full esptool.py command line as run: 
```
esptool.py -p COM4 --chip=esp32 read_mac
```
# Full output from esptool.py:
```
esptool.py v2.6
Serial port COM4
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
```
# What is the expected behaviour?
ESPTool should connect to the ESP32 device and retrieve MAC address.
# Do you have any other information from investigating this?

- **I can use the same hardware, connections, and computer on a Linux OS, and ESPTool works fine, every time.**
- This is the ```--trace``` output from Windows: https://drive.google.com/open?id=134nem08Gbyvfq-PUiLIC5K-53F3ZAxSM
- I am using an Adafruit CP2104 breakout as a USB to serial converter. I've uninstalled/reinstalled the Windows drivers for this.
- I've also uninstalled/reinstalled Python and ESPTool.
- My logic analyzer shows that the EN & IO0 signal for entering the bootloader toggles the same in both Windows and Linux:

**Windows:**
![image](https://user-images.githubusercontent.com/22217413/56383222-5d2bc500-61e7-11e9-8c42-7542061ba178.png)
[Saleae Logic Capture File](https://drive.google.com/file/d/1wYpUTCabX53ejqln2GDoKjF3eAirGv06/view?usp=sharing)

**Linux:**
![image](https://user-images.githubusercontent.com/22217413/56383330-95330800-61e7-11e9-9c85-d7cb01298e1f.png)
[Saleae Logic Capture File](https://drive.google.com/file/d/1dsUNBEBExAaMTrFmeQPTKHJX_IdVZTDo/view?usp=sharing)

**Comment by projectgus** [comment]
Hi @StevenLawsonBAF,

Thanks for the detailed report.

> My logic analyzer shows that the EN & IO0 signal for entering the bootloader toggles the same in both Windows and Linux:

This is unfortunately not what the capture shows. On Windows there is a couple of milliseconds delay after EN goes high and before IO0 goes low, and the ROM has started sending serial output before IO0 goes low (meaning the chip has already "bootstrapped" with IO0 high):

![windows_cap](https://user-images.githubusercontent.com/205573/56542611-5075eb00-65b2-11e9-85a2-82f57571f190.png)

On Linux the transitions happen at almost the exact same time:

![linux_cap](https://user-images.githubusercontent.com/205573/56542571-36d4a380-65b2-11e9-9913-2c14da5c4bcd.png)

This is mostly a limitation of Windows serial drivers and it's hard to work around.

It looks like the hardware board you are using has the "auto reset circuit", is that right? If so, add a capacitor between the EN and GND pins - anything in the range 100nF or higher should be enough. Most good quality development boards have this already, but some vendors still leave it off.

More details here: https://github.com/espressif/esptool/wiki/ESP32-Boot-Mode-Selection#automatic-bootloader

**Comment by projectgus** [comment]
Hi @StevenLawsonBAF ,

Did you get a chance to look at the reply above and try the capacitor mentioned?

If you have any other details about the auto-reset circuit in use, feel free to post them.

**Comment by StevenLawsonBAF** [comment]
@projectgus - thanks for your reply, and my apologies for not getting back to you sooner.

I did try adding a capacitor (as you mentioned), however it didn't solve the problem. That being said, I didn't spend much time troubleshooting with a logic analyzer or trying different capacitor values because I was able to bypass the issue by switching from the CP2104 to a FTDI-based USB->serial module, which seems to be working as expected.

I've attached the relevant bits of the schematic for the specific device I'm working with.

![I6_SB_ESP32_Circuit](https://user-images.githubusercontent.com/22217413/58446339-648b9b80-80ce-11e9-8eed-0010d3ca33c1.png)

**Comment by projectgus** [comment]
Thanks @StevenLawsonBAF . Did you add the capacitor between WIFI_EN & GND? I think because EN is driven with the AND gate in your design, it would need to be there to make any difference.

FTDI probably works because the Windows driver is setting the pins at roughly the same time, compared to the CP2102 driver.

I don't think there's anything we can do to fix this on the esptool.py side, unfortunately.

**Comment by projectgus** [comment]
Closing as I don't think we can do anything from the esptool.py side.
