### ISSUE TITLE
Compressed bin file for OTA update Question

### ISSUE THREAD

**Issue by kiralikbeyin** [espressif/esptool#451]
Wrote 665540 bytes (462839 compressed) at 0x00002000 in 40.8 seconds (effective 130.5 kbit/s)...

Is it possible to use compressed bin file for ota update?

I tried to use "make image" https://github.com/espressif/esptool/wiki/Advanced-Commands#make_image but didnt give compressed file..

How to make a compressed bin file.. ?

**Comment by projectgus** [comment]
Hi @kiralikbeyin ,

This is a good idea, but it's not something that can be done in esptool.

esptool compresses the file as it's being written to the device. esptool transparently gzips the contents and then it's un-gzipped on the chip as it's written to flash. There's no "compressed bin file" format, as such.

Compressed OTA is technically possible, and could be done with gzip in the same way. It would need to be added as a feature in whatever SDK or environment you are using, though. Please raise a feature request there to discuss it with them.
