### ISSUE TITLE
ESP32 power led blink and 2.2V coming from Pin 25/26- power supply 3v3 input

### ISSUE THREAD

**Issue by mmashraf** [espressif/esptool#452]
I have circuit connectivity for 220v status check.  220v  is connected to relay module Com Pin. then this 220v is applied to power supply module AC pins, now this power supply convert 220v to 3.3v. I have connected 3.3v supply pin to ESP32 Pin25.  This pin will show power level high when there is bulb or fan ON via relay module and visa versa.   All system is working ok when ESP32 is power on from USB cable.  When ESP32 is power off and some one ON the button of 220v bulb/fan,   There  is voltage level of 2.2-2.5 volts is coming on Pin 25 when I check the multi meter. and ESP32 remain off but power LED  of relay module is becoming ON  and ESP32 is also blinking, I also check that  power levels on 3.3v ESP pin is also high or 2.2v.  I have unable to identify the issue , I have changed ESP32 Pin 25 to 26 and also change power supply module . but still this strange behavior is happening with ESP32.  if I disconnect pin25 from ESP , all become Normal. it means that there is issue with ESP32, as 2.2v is at pin 25 is main cause of problem. this Pin25 is input mode and I can not avoid as in normal I have to decide light status at remote side with this input. only my issue is that 25/26 PIN input voltage is creating problem in ESP32 it self.
please advise so I can get out of this issue 
![image](https://user-images.githubusercontent.com/36144196/62460467-832ba400-b79b-11e9-8b8b-c4c746a3f9f4.png)

**Comment by projectgus** [comment]
Hi @mmashraf,

This is the issue tracker for the esptool.py project, and this question is not about esptool.py.

Suggest that the best place to ask this would be the ESP32 forums: https://esp32.com/

Please keep in mind that working with mains voltages is potentially lethal and requires some expertise to do safely.
