### ISSUE TITLE
Burn Custom Mac Address - Return error for trying burning a multicast address (ESPTOOL-96)

### ISSUE THREAD

**Issue by filzek** [espressif/esptool#472]
Latest.

One thing we findout now, the Burn custom mac allow to burn MULTICAST macaddress without warning or any prohibition, so, its case to analyze it before allow user to burn a MULTICAST mac address.

**Comment by radimkarnis** [comment]
Hello @filzek, 
thank you for reporting this. This is a valid concern, we will fix this.

Radim
