### ISSUE TITLE
Flashing problem

### ISSUE THREAD

**Issue by Maksss2018** [espressif/esptool#475]
Good day. I've flash  espruino on the lolin NodeMCU v3 with next command :
```
sudo python "../esptool/esptool.py" --port myUSB_PORT --baud 115200 write_flash --flash_freq 40m --flash_mode qio --flash_size 32m 0x0000 boot_v1.6.bin 0x1000 esprui
no_esp8266_user1.bin 0x3FC000 esp_init_data_default.bin 0x3FE000 blank.bin
```
then I connect to my board with  espruino client and it returned next : 
```
Espruino Command-line Tool 0.1.29
-----------------------------------

Connecting to '/dev/ttyUSB0'
No result found for "process.env" - just got ""
Unable to retrieve board information.
Connection Error?
Connected
```

board is ok - I've test it with AT , by connecting it to wifi but it's  real problem with espruino.

**Comment by projectgus** [comment]
Hi @Maksss2018 ,

Sorry noone got back to you earlier.

As you say, this is a problem with Espruino. You'll need to refer to the Espruino docs or find Espruino support site to help you.

esptool.py is just the tool that flashes the firmware on the board, and this step seems to be working.
