### ISSUE TITLE
Lazy loading of serial module

### ISSUE THREAD

**Issue by cmaglie** [espressif/esptool#477]
Is it possible to load the `serial` module only when actually used?

We had an issue report [here](https://github.com/arduino/arduino-cli/issues/455), basically the user is trying to run a build on a CI container that by default doesn't have `pyserial` installed, I guess that `esptool` in this case is used only to build the binary artifact, but it loads `pyserial` anyway.

Not a big deal, the workaround is easy (just install pyserial...), but it would be nice to require `pyserial` only when really needed.

**Comment by projectgus** [comment]
Hi @cmaglie ,

Thanks for forwarding this request.

The recommended way to install esptool is via pip, and if installed via pip then pyserial is installed already.

Arduino ESP32 core uses a bundled esptool not a version from pip, but the instructions for installing [the ESP32 Core](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/debian_ubuntu.md) include a step for installing pyserial via pip.

So this is probably a wontfix from the esptool side as well, given that tracking this additional state in esptool means additional code-level complexity - and the workaround is, as you say, pretty straightforward.
