### ISSUE TITLE
esptool write_flash: error: argument <address> <filename>: Must be pairs of an address and the binary filename to write there  SPIFFS Upload failed!

### ISSUE THREAD

**Issue by CharlesSee** [espressif/esptool#486]
* Operating system: Windows 10
* Python version: 3.8
* ESP hardware in use: Bigtree ESP-01S
I have uploaded the default esp3d.ino to the ESP8266, and have the "ESP3D" appearing in my wifi list on my phone.
I'm trying to create the SPIFFS File system section on the EESP8266.
In arduino IDE 1.8.10, When I click tools, Sketch Data Upload, I get the below message. 
I have no idea how to correct this message or get the SPIFFS loaded..
All the youtube videos and tutorials I have seen just show the upload.py working without errors.

-------------------------------------------------------------------------------
[SPIFFS] data    : C:\Users\Charles\AppData\Local\Temp\untitled551208617.tmp\sketch_nov23a\data
[SPIFFS] size    : 512
[SPIFFS] page    : 256
[SPIFFS] block   : 8192
[SPIFFS] upload  : C:\Users\Charles\AppData\Local\Temp\arduino_build_457769/sketch_nov23a.spiffs.bin
[SPIFFS] address  : 0x7B000
[SPIFFS] reset    : --before default_reset --after hard_reset
[SPIFFS] port     : COM3
[SPIFFS] speed    : 115200
[SPIFFS] python   : C:\Users\Charles\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\tools\python.exe
[SPIFFS] uploader : C:\Users\Charles\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\tools\upload.py

usage: esptool write_flash [-h] [--erase-all]

                           [--flash_freq {keep,40m,26m,20m,80m}]
                           [--flash_mode {keep,qio,qout,dio,dout}]
                           [--flash_size FLASH_SIZE]
                           [--spi-connection SPI_CONNECTION] [--no-progress]
                           [--verify] [--encrypt]
                           [--ignore-flash-encryption-efuse-setting]
                           [--compress | --no-compress]
                           <address> <filename> [<address> <filename> ...]

esptool write_flash: error: argument <address> <filename>: Must be pairs of an address and the binary filename to write there

SPIFFS Upload failed!
---------------------------------

**Comment by projectgus** [comment]
Hi @CharlesSee ,

This has something to do with the command line being generated by Arduino IDE, it's not generating a valid esptool.py command line. There's nothing we can do to fix this from the esptool side. 

Please report it to the Arduino ESP8266 project: https://github.com/esp8266/arduino/issues
