### ISSUE TITLE
Can't upload to SPIFFS with 2.6.2

### ISSUE THREAD

**Issue by kfeger** [espressif/esptool#488]
I try to upload to SPIFFS. That fails with the trace below.  Upload to Flash works fine, also both Flash and SPIFFS upload work fine with same hardware under 2.5.2. System is Win10Pro

Trace:
**********************************************
[SPIFFS] data    : C:\Users\Besitzer\Documents\Arduino18-xeon\ESP_ISS\data
[SPIFFS] size    : 192
[SPIFFS] page    : 256
[SPIFFS] block   : 4096
/index.html
/ISS150.png
/settings.html
/setup.png

[SPIFFS] upload  : C:\Users\Besitzer\AppData\Local\Temp\arduino_build_372128/ESP_ISS.spiffs.bin
[SPIFFS] address  : 0xCB000
[SPIFFS] reset    : --before default_reset --after hard_reset
[SPIFFS] port     : COM6
[SPIFFS] speed    : 115200
[SPIFFS] python   : python.exe
[SPIFFS] uploader : C:\Users\Besitzer\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\tools\upload.py

usage: esptool [-h] [--chip {auto,esp8266,esp32}] [--port PORT] [--baud BAUD]

               [--before {default_reset,no_reset,no_reset_no_sync}]

               [--after {hard_reset,soft_reset,no_reset}] [--no-stub]

               [--trace] [--override-vddsdio [{1.8V,1.9V,OFF}]]

               {load_ram,dump_mem,read_mem,write_mem,write_flash,run,image_info,make_image,elf2image,read_mac,chip_id,flash_id,read_flash_status,write_flash_status,read_flash,verify_flash,erase_flash,erase_region,version}
               ...

esptool: error: unrecognized arguments: --end

SPIFFS Upload failed!
************************************************

# Operating system
Win10Pro
# Python version
3.8.0
Can run `python -V` to check this.

# What Chip
ESP-01, ESP8266 1MB (detected)
(For example: ESP8266, ESP32-PICO-D4, ESP32-WROOM32 module, etc)

# What development board or other hardware is the chip attached to
homebrew, works fine with 2.5.2
(For example: DevKitC, NodeMCU board, plain module on breadboard, etc)

If your hardware is custom or unusual, please attach a photo to the issue.

# Is anything else attached to the development board, except for the serial flasher connections?
no
Example: GPIO 18 & 19 are connected to I2C devices.

# Are you running esptool.py from an IDE such as Arduino or Eclipse?
Arduino 1.8.10
Example: No IDE, Windows command prompt

Example 2: Arduino ESP8266 IDE version 2.5.77

# Full esptool.py command line that was run:

esptool.py -p COM999 write_flash 0x0 bootloader.bin

# Full output from esptool.py
[SPIFFS] data    : C:\Users\Besitzer\Documents\Arduino18-xeon\ESP_ISS\data
[SPIFFS] size    : 192
[SPIFFS] page    : 256
[SPIFFS] block   : 4096
/index.html

/ISS150.png

/settings.html

/setup.png

[SPIFFS] upload  : C:\Users\Besitzer\AppData\Local\Temp\arduino_build_372128/ESP_ISS.spiffs.bin
[SPIFFS] address  : 0xCB000
[SPIFFS] reset    : --before default_reset --after hard_reset
[SPIFFS] port     : COM6
[SPIFFS] speed    : 115200
[SPIFFS] python   : python.exe
[SPIFFS] uploader : C:\Users\Besitzer\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\tools\upload.py

usage: esptool [-h] [--chip {auto,esp8266,esp32}] [--port PORT] [--baud BAUD]

               [--before {default_reset,no_reset,no_reset_no_sync}]

               [--after {hard_reset,soft_reset,no_reset}] [--no-stub]

               [--trace] [--override-vddsdio [{1.8V,1.9V,OFF}]]

               {load_ram,dump_mem,read_mem,write_mem,write_flash,run,image_info,make_image,elf2image,read_mac,chip_id,flash_id,read_flash_status,write_flash_status,read_flash,verify_flash,erase_flash,erase_region,version}

               ...

esptool: error: unrecognized arguments: --end

SPIFFS Upload failed!

# Do you have any other information from investigating this?

Example: The command succeeds 1 in every 3 tries
Upload works under 2.5.2

# Is there any other information you can think of which will help us reproduce this problem?

Example: I also have a Windows 95 PC, esptool command works correctly on this PC.

**Comment by kfeger** [comment]
2.6.1 gives the same error. 2.6.0 works fine. Here the output from 2.6.0
****************************
[SPIFFS] data    : C:\Users\Besitzer\Documents\Arduino18-xeon\ESP_ISS\data
[SPIFFS] size    : 192
[SPIFFS] page    : 256
[SPIFFS] block   : 4096
/index.html

/ISS150.png

/settings.html

/setup.png

[SPIFFS] upload  : C:\Users\Besitzer\AppData\Local\Temp\arduino_build_372128/ESP_ISS.spiffs.bin
[SPIFFS] address  : 0xCB000
[SPIFFS] reset    : --before default_reset --after hard_reset
[SPIFFS] port     : COM6
[SPIFFS] speed    : 115200
[SPIFFS] python   : python.exe
[SPIFFS] uploader : C:\Users\Besitzer\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.0\tools\upload.py

esptool.py v2.7

Serial port COM6

Connecting....

Chip is ESP8266EX

Features: WiFi

Crystal is 26MHz

MAC: 18:fe:34:dc:ff:42

Uploading stub...

Running stub...

Stub running...

Configuring flash size...

Auto-detected Flash size: 1MB

Compressed 196608 bytes to 60539...


Writing at 0x000cb000... (25 %)
Writing at 0x000cf000... (50 %)
Writing at 0x000d3000... (75 %)
Writing at 0x000d7000... (100 %)
Wrote 196608 bytes (60539 compressed) at 0x000cb000 in 5.3 seconds (effective 294.0 kbit/s)...

Hash of data verified.

**Comment by projectgus** [comment]
Hi @kfeger ,

```
esptool: error: unrecognized arguments: --end
```

The problem is the command line that Arduino IDE is building when it runs esptool.py. There isn't anything that can be done about it from the esptool.py side, the Arduino IDE has to send a valid command.

This issue suggests that if you update the Upload plugin in Arduino then it will fix it: https://github.com/esp8266/Arduino/issues/6864

**Comment by kfeger** [comment]
Hi Angus,

I downloaded the new Upload plugin. But since I’m by no means a Java person: How do I come from the supplied ESP8266FS.java tot the needed .jar file? Make.sh will not work under Win10…

 

Von: Angus Gratton <notifications@github.com> 
Gesendet: Montag, 2. Dezember 2019 03:56
An: espressif/esptool <esptool@noreply.github.com>
Cc: Karl O. Feger <kfeger@yahoo.de>; Mention <mention@noreply.github.com>
Betreff: Re: [espressif/esptool] Can't upload to SPIFFS with 2.6.2 (#488)

 

Hi @kfeger <https://github.com/kfeger>  ,

esptool: error: unrecognized arguments: --end

The problem is the command line that Arduino IDE is building when it runs esptool.py. There isn't anything that can be done about it from the esptool.py side, the Arduino IDE has to send a valid command.

This issue suggests that if you update the Upload plugin in Arduino then it will fix it: esp8266/Arduino#6864 <https://github.com/esp8266/Arduino/issues/6864>

**Comment by kfeger** [comment]
Sorry to disturb again but: Got it. Version 0.5 works fine.

Karl

 

Von: Angus Gratton <notifications@github.com> 
Gesendet: Montag, 2. Dezember 2019 03:56
An: espressif/esptool <esptool@noreply.github.com>
Cc: Karl O. Feger <kfeger@yahoo.de>; Mention <mention@noreply.github.com>
Betreff: Re: [espressif/esptool] Can't upload to SPIFFS with 2.6.2 (#488)

 

Hi @kfeger <https://github.com/kfeger>  ,

esptool: error: unrecognized arguments: --end

The problem is the command line that Arduino IDE is building when it runs esptool.py. There isn't anything that can be done about it from the esptool.py side, the Arduino IDE has to send a valid command.

This issue suggests that if you update the Upload plugin in Arduino then it will fix it: esp8266/Arduino#6864 <https://github.com/esp8266/Arduino/issues/6864>
