### ISSUE TITLE
AttributeError: 'ESP8266StubLoader' object has no attribute 'secure_download_mode'

### ISSUE THREAD

**Issue by corvese** [espressif/esptool#531]
# Operating system
* Windows 10 64-bit

# Python version
* 3.6.5

# What Chip

* ESP8266

# What development board or other hardware is the chip attached to

NodeMCU board - SeeKool ESP8266 NodeMcu LUA WiFi Module CP2102 ESP-12E Development Board

# Is anything else attached to the development board, except for the serial flasher connections?

No - Only a MicroUSB cable. Was not connected to a breadboard or any additional connections

# Are you running esptool.py from an IDE such as Arduino or Eclipse?

No, windows command prompt in a directory that has a git clone of esptool

# Full esptool.py command line that was run:

`C:\Users\corve\Desktop\esptool>esptool.py --port COM7 --baud 460800 write_flash --flash_size=detect -fm dio 0 esp8266-20191220-v1.12.bin`

Command recommendations were taken from: [link](http://docs.micropython.org/en/latest/esp8266/tutorial/intro.html#deploying-the-firmware)

# Full output from esptool.py

Failed here initially - line 2506 of esptool.py:

```
C:\Users\corve\Desktop\esptool>esptool.py --port COM7 --baud 460800 write_flash --flash_size=detect -fm dio 0 esp8266-20191220-v1.12.bin
esptool.py v3.0-dev
Serial port COM7
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 4c:11:ae:0a:c7:cd
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Traceback (most recent call last):
  File "C:\Users\corve\Desktop\esptool\esptool.py", line 3544, in <module>
    _main()
  File "C:\Users\corve\Desktop\esptool\esptool.py", line 3537, in _main
    main()
  File "C:\Users\corve\Desktop\esptool\esptool.py", line 3244, in main
    detect_flash_size(esp, args)
  File "C:\Users\corve\Desktop\esptool\esptool.py", line 2506, in detect_flash_size
    if esp.secure_download_mode:
AttributeError: 'ESP8266StubLoader' object has no attribute 'secure_download_mode'
```

THEN I commented out 2506 and 2507 on esptool.py and it failed:

```
C:\Users\corve\Desktop\esptool>esptool.py --port COM7 --baud 460800 write_flash --flash_size=4MB -fm dio 0 esp8266-20191220-v1.12.bin
esptool.py v3.0-dev
Serial port COM7
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 4c:11:ae:0a:c7:cd
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Flash params set to 0x0240
Compressed 619828 bytes to 404070...
Wrote 619828 bytes (404070 compressed) at 0x00000000 in 9.6 seconds (effective 513.9 kbit/s)...
Traceback (most recent call last):
  File "C:\Users\corve\Desktop\esptool\esptool.py", line 3544, in <module>
    _main()
  File "C:\Users\corve\Desktop\esptool\esptool.py", line 3537, in _main
    main()
  File "C:\Users\corve\Desktop\esptool\esptool.py", line 3249, in main
    operation_func(esp, args)
  File "C:\Users\corve\Desktop\esptool\esptool.py", line 2668, in write_flash
    if not args.encrypt and not esp.secure_download_mode:
AttributeError: 'ESP8266StubLoader' object has no attribute 'secure_download_mode'
```
It appears that an object is not being initialized properly or an attribute of an instance is not being assigned properly?

# Do you have any other information from investigating this?

Yes, when I checked out git commit 988b9a2 (1 commit before this secure boot feature appears to have been implemented in 45e2deb) and I re-ran the aforementioned commands, it appears to be successful. See output:

```
C:\Users\corve\Desktop\esptool>esptool.py --port COM7 --baud 460800 write_flash --flash_size=detect -fm dio 0 esp8266-20191220-v1.12.bin
esptool.py v3.0-dev
Serial port COM7
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 4c:11:ae:0a:c7:cd
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0240
Compressed 619828 bytes to 404070...
Wrote 619828 bytes (404070 compressed) at 0x00000000 in 9.6 seconds (effective 514.2 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

**Comment by projectgus** [comment]
Hi @corvese ,

Thanks for the detailed bug report. You're right that this flag isn't being initialized correctly for ESP8266 (where it should always be False), will fix.

In the meantime using the commit you're using, or checking out the stable release (`git checkout v2.8`) is a good workaround.
