### ISSUE TITLE
(GPIO12) Has internal pull-down, so unconnected = Low = 3.3V

### ISSUE THREAD

**Issue by trimarco232** [espressif/esptool#535]
right ?

**Comment by projectgus** [comment]
Hi @trimarco232,

Please don't use the esptool issue tracker for general questions. Questions about ESP32 can be asked at https://esp32.com .

The title of this question is copy/pasted from the wiki page here:
https://github.com/espressif/esptool/wiki/ESP32-Boot-Mode-Selection#other-pins

This information is correct. You can confirm it by looking at ESP32 Datasheet section "2.4 Strapping Pins". Note GPIO12 is also named MTDI.

Note also that not every ESP32 device has a 3.3V flash chip attached, some ESP32s have 1.8V flash chips attached and GPIO12 must be pulled up to avoid over-voltage of the chip.

The documentation or schematic for whatever device you have should clarify this.
