### ISSUE TITLE
Lerlink X802A-RF Flash tasmota failed.

### ISSUE THREAD

**Issue by horacecar** [espressif/esptool#562]
Cannot flash tasmota with wall switch

![1](https://user-images.githubusercontent.com/44496483/93636376-65b0ac80-fa26-11ea-8016-ef0c53c0ad16.png)
![2](https://user-images.githubusercontent.com/44496483/93636543-ac060b80-fa26-11ea-8d1d-ff43abb858d5.png)

**Comment by projectgus** [comment]
Hi @horacecar ,

If the COM port is correct, this is a hardware issue of some kind. Suggest working through the troubleshooting list mentioned here:
https://github.com/espressif/esptool#Troubleshooting

Angus
