### ISSUE TITLE
Add arg to main function espefuse.py (ESPTOOL-109)

### ISSUE THREAD

**Issue by tcolin65** [espressif/esptool#563]
Could you add arg to main function in espefuse.py, please ? Like the main function in esptool.py
Example :  "def main(custom_commandline=None):"  + add the arg "args = parser.parse_args(custom_commandline)".

In order to execute this script from python.

Thank in advance,

**Comment by radimkarnis** [comment]
Hello @tcolin65, 

thank you for the feature proposal. This indeed makes very good sense and I've created an internal task to implement this in the near future.

Radim
