### ISSUE TITLE
Linker can't link | Undefined reference to function

### ISSUE THREAD

**Issue by X0rrify** [espressif/esptool#566]
* Operating system: Windows 10
* Python version: 3.8.5

# Full esptool.py command line as run:
esptool.py v2.6

# Full output from esptool.py

Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html
PLATFORM: Espressif 32 (2.0.0) > DOIT ESP32 DEVKIT V1
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10004.200129 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 26 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio\build\esp32doit-devkit-v1\src\yoyo.cpp.o
Linking .pio\build\esp32doit-devkit-v1\firmware.elf
.pio\build\esp32doit-devkit-v1\src\yoyo.cpp.o:(.literal._Z4loopv+0x4): undefined reference to `transfer_yoyo()'
.pio\build\esp32doit-devkit-v1\src\yoyo.cpp.o: In function `loop()':
C:\Projects\Yoyo/src/yoyo.cpp:54: undefined reference to `transfer_yoyo()'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32doit-devkit-v1\firmware.elf] Error 1
====================================================================== [FAILED] Took 3.66 seconds 

# What is the expected behaviour?

Compile and link successfully.

# Do you have any other information from investigating this?

The project consist of 2 source files and 2 header files located at the same place, the src directory.
The main file is yoyo.cpp and the other one acx.c.
The function transfer_yoyo is located at the acx.c file.
And I'm calling it from inside the main loop().
I also tried putting the external pair in the include and lib directories but the result is the same.
The linker can't link the objects.

**Comment by projectgus** [comment]
Hi @X0rrify,

I'm afraid this error message is coming when compiling code in platform.io.

esptool is just the Python program that generates the .bin file from the linked .elf, and flashes the linked binary onto the device. It's not involved in producing this error message.

Suggest trying some of the support resources over at https://platformio.org/

**Comment by X0rrify** [comment]
Thanks.
