### ISSUE TITLE
Documentation: MB or MiB? (ESPTOOL-143)

### ISSUE THREAD

**Issue by rtek1000** [espressif/esptool#571]
Hi, I was burning ESP-Link on an ESP8266, and I noticed that 4MB is now expected instead of 32m.

But I have a doubt, I found a list of specifications for ESP8266 that quoted MiB instead of MB.

And this confusion started in 1998, if I'm not mistaken.

In the case of esptool, wouldn't it be correct to use MiB for flash memory?

> External QSPI flash: up to 16 MiB is supported (512 KiB to 4 MiB typically included)

https://en.m.wikipedia.org/wiki/ESP8266

> write_flash -fs 32m

https://github.com/jeelabs/esp-link/blob/master/FLASHING.md#initial-serial-flashing

https://en.m.wikipedia.org/wiki/Mebibyte

**Comment by projectgus** [comment]
Hi @rtek1000,

Yes, you're right - the units in esptool are all power of two units, so in IEC units the esptool v1.x size arguments are Mebibits and the v2.0 and newer arguments are Mebibytes. 

Manufacturers of SPI NOR Flash (as used by ESP8266) typically specify their products in Megabits (Mb), which according to the IEC should be Mebibits (Mib). But no memory manufacturer seems to use Mib.

Espressif's own technical documentation doesn't use the Mebi- prefix either. (For example: [ESP8266 datasheet uses MB to mean the power of 2 unit](https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf), whoever put this information on Wikipedia changed it to MiB.)

For compatibility reasons and to keep consistent with the flash manufacturers we probably won't change the command line arguments, but this is something that can be noted in the esptool docs to avoid any confusion.
