### ISSUE TITLE
ESP32S2 is not support in current release version? 

### ISSUE THREAD

**Issue by ladyada** [espressif/esptool#572]
hi its been a year since the latest release. Please bump pypi so folks with ESP32S2 can progam chips with esptool

**Comment by projectgus** [comment]
Hi @ladyada,

You have fantastic timing! :)

https://github.com/espressif/esptool/releases/tag/v3.0

https://pypi.org/project/esptool/3.0/

(There is an issue just noticed where - at least one some platforms - an error `error: invalid command 'bdist_wheel'` is printed when running "pip install esptool". The error doesn't break the installation in any way. Will fix this ASAP, but it can be ignored for now.)

Angus

**Comment by ladyada** [comment]
yayayayay best news all day :) :)
