### ISSUE TITLE
Unlisted dependency on setuptools, python-dev, libffi-dev (ESPTOOL-168)

### ISSUE THREAD

**Issue by Narvey** [espressif/esptool#585]
* Operating system: Armbian buster (Debian 10)
* Python version: 2.7.16

# Full esptool.py command line as run:
pip2 install esptool

# Full output from ~~esptool.py~~ pip
Collecting esptool
  Using cached https://files.pythonhosted.org/packages/dd/3d/d1d4c004927e6e6807c441ce70330ed969c725d2906053fbd2ff994b4439/esptool-3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-v4nV1D/esptool/

# What is the expected behaviour?
I don't know how python packages work, but every other package has the concept of dependencies, that will install before attempting to install the requested package. If you can do this with pip, please mark setuptools as a required (or prerequisite or whatever) dependency.
After getting over that, I had to install (in turn, with a google cycle each time) python-dev, then libffi-dev. These should probably be installed before any pip command is run (right? can you put this in the installation instructions instead of assuming pip install esptool will work?)
Please investigate if there are any other requirements. The last go-round I got a message (warning?):
`Failed building wheel for cffi`
for cffi and for other packages, but it still seemed to install. Should this concern me?

# Do you have any other information from investigating this?
The workaround is (as root):
```
apt update && apt install -y python-dev libffi-dev
pip2 install setuptools
pip2 install esptool
```

# Is there any other information you can think of which will help us reproduce this problem?
You should be able to reproduce at least some of it anywhere setuptools is not installed.

**Comment by radimkarnis** [comment]
Hello @Narvey,
thank you for reporting this. We will update the README file.
The "Failed building wheel for X" message shouldn't concern you (see [this answer](https://stackoverflow.com/a/56504270)).

Radim
