### ISSUE TITLE
esptool and deprecation of Python 2

### ISSUE THREAD

**Issue by Martin-Laclaustra** [espressif/esptool#596]
Due to deprecation of Python 2 some Linux distributions have decided to remove the generic "python" executable from the path, forcing all code to explicitly declare which version of Python they require (A wise solution in my opinion, as it serves as "canary" for undefined code and prevents obscure errors, resolving the longstanding ambiguity, and still allows the use of older python 2 code). This change has been annoying when one's mind is in other tasks, but one must adapt to new times and deprecation was announced years ago.
I was proposing to change the shebang to `#!/usr/bin/env python3` here https://github.com/espressif/arduino-esp32/issues/4717 but me-no-dev suggested that a global upstream action might be suitable.

Best regards.

**Comment by dobairoland** [comment]
Hi @Martin-Laclaustra. My answer is essentially the same as in https://github.com/espressif/esp-idf/issues/6421#issuecomment-762054562.

Esptool still supports Python 2 and the suggested change would break code for customers stuck with Python 2, eg. old computers in factories used only for flashing.
