### ISSUE TITLE
Outdated flash size documentation in README (ESPTOOL-193)

### ISSUE THREAD

**Issue by marcelstoer** [espressif/esptool#599]
https://github.com/espressif/esptool#flash-size---flash_size--fs says

> The default `--flash_size` parameter is `detect`

https://github.com/espressif/esptool/releases/tag/v3.0, however, says

> The default `esptool.py write_flash --flash_size` argument has changed from `detect` to `keep`.

Can I assume the README is simply outdated in this respect?

**Comment by radimkarnis** [comment]
Hello @marcelstoer,

thank you for opening this issue.
You are indeed right, the README file hasn't been updated to reflect this change.

Will fix this ASAP.
