### ISSUE TITLE
A command for BINARY to ELF (ESPTOOL-200)

### ISSUE THREAD

**Issue by rohitsam** [espressif/esptool#604]
Although there is a command image_info, which doesn't give many details about the flash dump.

A feature for analyzing a flash dump of esp8266 and esp32.
It would be great if there is support for converting **BINARY to ELF** file which could be helpful for analyzing the flash dump of esp8266 or esp32 much easily.

There is some work done on this but is outdated [ESP-BIN2ELF](
https://github.com/jsandin/esp-bin2elf)

**Comment by dobairoland** [comment]
Hi @rohitsam. Thank you for raising this feature request but I'm sorry to tell you that supporting reverse engineering of our binaries is not planned and is not our priority.
