### ISSUE TITLE
[S2] flash over USB (ESPTOOL-209)

### ISSUE THREAD

**Issue by chegewara** [espressif/esptool#609]
Hi @dobairoland 
Recently i reported issue with flashing S2 over USB on windows 10 but there was not enough data to think it is esptool issue. Today i performed another test with `USBlyzer` app on windows and i think it may shade some light on the problem.
As far as i understand logs from that app, esptool is sending a lot od `Set line codding requests` and then `Get line codding requests`. 
I think the problem occurs when S2 is already in `waiting download mode`, but esptool is still sending `Get coding line requests`. It is not a problem when cp210x is in the middle, but S2 cant respond on that and esptool is just resting connection.

I understand it work when rom USB is used, but in that case i the 1st stage bootloader is responding, even when CPU is in download mode.

![Screenshot from 2021-03-11 16-36-45](https://user-images.githubusercontent.com/1406020/110812700-2140f380-8288-11eb-82d1-6c7c8741127e.png)

**Comment by dobairoland** [comment]
Thank you! I will debug this and try to come up with a solution. I probably get to this the next week.

**Comment by chegewara** [comment]
And example of flashing using arduino IDE, when on S2 was installed `console_usb` example:
![Screenshot from 2021-03-11 16-49-34](https://user-images.githubusercontent.com/1406020/110814500-ca3c1e00-8289-11eb-8cab-2d30d55e5e82.png)

**Comment by dobairoland** [comment]
> ... I will debug this and try to come up with a solution. I probably get to this the next week.

The priorities has been changed so I can look at this in the next couple of weeks.

**Comment by radimkarnis** [comment]
Hello @chegewara,
I tried to investigate, but couldn't manage to reproduce this issue. Would you mind explaining the steps in detail?
Thank you very much

**Comment by chegewara** [comment]
Sorry for not updating issue. Recently arduino has been updated and all seems to be ok, at least when i tested with arduino-esp32 v2.0.0-alpha1 on windows 10 VM.
I didnt test with esp-idf on linux yet, but i am assuming it is ok right now. If i will have problems i will reopen issue.

Thanks

**Comment by radimkarnis** [comment]
I appreciate your timely response. Closing this issue.
