### ISSUE TITLE
support for ESPhome (ESPTOOL-212)

### ISSUE THREAD

**Issue by TwinsenLiang** [espressif/esptool#612]
**Is your feature request related to a problem? Please describe.**
I use ESPHome to build a Bin file in Home Assistant.and chose "Espressif ESP32 Dev Module" with the Device type.then I use nodeMCU to Flash the "ESP32 One" which the waveshare sold me.then it can not work.

**Describe the solution you'd like**
I hope u to support for ESPhome.it can easy to let designer get into the Iot world.

**Additional context**
rst:0x10 (RTCWDT_RTC_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
invalid header: 0x00000000
invalid header: 0x00000000
invalid header: 0x00000000
invalid header: 0x00000000
invalid header: 0x00000000
invalid header: 0x00000000
invalid header: 0x00000000
ets Jul 29 2019 12:21:46

**Comment by dobairoland** [comment]
Hi @TwinsenLiang. Please report your issue and feature request for ESPHome. Esptool can flash all ESP chips. Any incompatibility must be handled at the ESPHome level. Thank you for your understanding.
