### ISSUE TITLE
Impossible to consult the esptool's version (ESPTOOL-232)

### ISSUE THREAD

**Issue by kristofmulier** [espressif/esptool#624]
I tried to consult the version of the `esptool.py` script:

```sh
$ python esptool.py -v
esptool: error: unrecognized arguments: -v
```

and:
```sh
$ python esptool.py --version
esptool: error: unrecognized arguments: -version
```

I think it's an important feature. Most software let their users consult the version nr this way.

**Comment by kristofmulier** [comment]
Apparently, it works without a `'-'`, so like this:

```sh
$ python esptool.py version
```

My apologies.

**Comment by radimkarnis** [comment]
Hello @kristofmulier,
indeed, the option to display the current version is implemented as a command, not an optional argument. See the esptool help screen for clarification.
There is an ongoing initiative to improve esptool docs, we will make sure to properly document this option.
