### ISSUE TITLE
ESPEFUSE - 'burn_block_data' Failure (ESPTOOL-235)

### ISSUE THREAD

**Issue by t0rxe** [espressif/esptool#627]
Hi,

I flashed to BLOCK3 0xFF on all 32 bytes, and now when I try to erase it back to anything I get an error (seen below).
It seems that it refuses to overwrite 0xFF.

Here is what I'm trying to do:
**py espefuse.py burn_block_data BLOCK3 null_0.dat -p COM31 --force-write-always**

```
Connecting....
Detecting chip type... ESP32
espefuse.py v3.1-dev
[03] BLOCK3               size=32 bytes, offset=00 - > [ed 49 4f 54 00 00 00 00 00 00 ... 0].

Check all blocks for burn...
idx, BLOCK_NAME,          Conclusion
[03] BLOCK3               is not empty
        (written ): 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        (to write): 0x00000000000000000000000000000000eb73f5050000000000000000544f49ed
        All wr_data bits are set in the written block, continue with EMPTY_BLOCK.
Nothing to burn, see messages above.
Successful
```

Operating system is Windows 7 (32-bit) with Python 3.8.

**Comment by dobairoland** [comment]
Hi @t0rxe. I'm sorry to tell you that what you are intend to do is not possible. An eFuse can be programmed to 1 but cannot be reverted back to 0. Your block will remain all 1s. 

Please read chapter 20 of the [TRM](https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf) for more information.
