### ISSUE TITLE
Nonexistent link anchor inside README (ESPTOOL-270)

### ISSUE THREAD

**Issue by JosefKuchar** [espressif/esptool#641]
The "boot log" link inside Common Options > Baud rate is broken
![image](https://user-images.githubusercontent.com/12010072/125453819-e08f78f6-fe07-4a3e-b02b-45a0cf00134e.png)

**Comment by radimkarnis** [comment]
Hello @JosefKuchar,

thanks for letting us know! This will be fixed in a future README/documentation update.

Radim
