### ISSUE TITLE
How can I upload to ESP32 board via OTG-USB from Android? (ESPTOOL-314)

### ISSUE THREAD

**Issue by jinwook4217** [espressif/esptool#665]
There was a problem in using esptool directly on Android because it was written in Python code.

So, what we are curious about is how to use esptool to learn more about how to upload to ESP32/ESP8266 board via USB from Android device via OTG.

Is it possible to run esptool code as cli command on Android?
Do I have to port all esptool code to java/kotlin?
Is there any open source to upload from android device using esptool ?

Sorry for the off-topic issue.

**Comment by dobairoland** [comment]
I'm sorry, this is not supported. I can suggest to search for a solution of running a Python script from Android.

Beside that here is a list of other implementations which could help:
- [esptool-js](https://github.com/espressif/esptool-js) can run from a browser.
- There is also a C-based implementation: https://github.com/espressif/esp-serial-flasher
- Rust implementation is under development: https://github.com/esp-rs/esp-flash-loader
- Windows gui application: https://www.espressif.com/en/support/download/other-tools

However, none of the mentioned implementations offers the full set of features of Esptool.

**Comment by bdureau** [comment]
It would be really good to have it on android. I am building android applications that are uploading the latest firmware to many microcontrolers to make sure that my Android front end is compatible with the firmware . I have looked at many ESPTools applications in javascript or C# and I have tried to use the Physicaloid library to do an Android port and it is hardwork. I am trying to do the sync and I am not getting any response from the ESP32 .... Could it be possible to explain how the Python program works. Why do you need to encapsulate frames and replace some bytes such as 0xC0 by 0xDB and 0xDC?

**Comment by radimkarnis** [comment]
Hi @bdureau,
the serial protocol used by esptool is explained [here](https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/serial-protocol.html). This page also explains SLIP packet framing, which is the reason why some bytes are being replaced.

**Comment by bdureau** [comment]
Thanks I am taking a look at it

**Comment by bdureau** [comment]
If anybody has started a port on Android or java please contact me

**Comment by bdureau** [comment]
Ok here is my issue. I just cannot get it to sync. I have tried with 2 different USB libraries (libUSB and Physicaloid) and it does not respond at all. I have set the baudrate to 115200
I am doing the reset and boot mode manually using the button. I can print a message which says "waiting for download"
Here is my code. I would appreciate if you could help
int sync() {
        int x;
        int response = 0;
        byte cmddata [] = new byte[36];

        cmddata[0] =  (byte)(0x07);
        cmddata[1] =  (byte)(0x07);
        cmddata[2] =  (byte)(0x12);
        cmddata[3] =  (byte)(0x20);
        for (x = 4; x < 36; x++)
        {
            cmddata[x] =  (byte)(0x55);
        }

        for (x = 0; x < 7; x++)
        {

            byte cmd =(byte)0x08;
            sendCommand(cmd, cmddata, 0);
        }
        return response;
    }
    void sendCommand(byte opcode, byte buffer[], int chk) {
        int CorrectReply = 0;

        int i = 0;
        byte data[]= new byte[8+buffer.length];
        data[0] =  (byte)0x00;
        data[1] =  opcode;
        data[2] = (byte) ((buffer.length )&0xFF);
        data[3] = (byte)((buffer.length >> 8)&0xFF );
        data[4] = (byte)((chk&0xFF) );
        data[5] = (byte)((chk >> 8)&0xFF) ;
        data[6] = (byte)((chk >> 16)&0xFF) ;
        data[7] = (byte)((chk >> 24) &0xFF);
        for (i = 0; i < buffer.length; i++) {
            data[8 + i] = buffer[i];
        }
        usbService.write(slipEncode(data));
    }
    byte[] slipEncode(byte buffer[]) {
        int ESP_FLASH_BLOCK = 0x400;
        int i = 0;
        byte encoded[] = new byte[ESP_FLASH_BLOCK * 2];
        encoded[i] = (byte) 0xC0;

        for (int x = 0; x < buffer.length; x++)
        {
            if (buffer[x] == (byte) (0xC0)) { encoded[i++] = (byte)(0xDB); encoded[i++] =(byte) (0xDC); }
            else if (buffer[x] == (byte) (0xDB)) { encoded[i++] = (byte)(0xDB); encoded[i++] = (byte)(0xDD); }
            else { encoded[i++] = buffer[x]; }
        }
        encoded[i++] = (byte)(0xC0);
        return buffer;
    }

**Comment by bdureau** [comment]
Hello all
I have done a quick  Java port of the Esptool. Currently only working on ESP32
https://github.com/bdureau/ESPLoader

I am planning on porting it to Android so that it can flash my firmware from my phone

**Comment by bdureau** [comment]
I have also done a port to Android using the physicaloid lib 
https://github.com/bdureau/BearConsole2/tree/master/app/src/main/java/com/altimeter/bdureau/bearconsole/Flash
However it needs improvement, I have added some timers so that it worked .... but is is slow!!!!

**Comment by TheButlah** [comment]
> I'm sorry, this is not supported. I can suggest to search for a solution of running a Python script from Android.
> 
> Beside that here is a list of other implementations which could help:
> 
>     * [esptool-js](https://github.com/espressif/esptool-js) can run from a browser.
> 
>     * There is also a C-based implementation: https://github.com/espressif/esp-serial-flasher
> 
>     * Rust implementation is under development: https://github.com/esp-rs/esp-flash-loader
> 
>     * Windows gui application: https://www.espressif.com/en/support/download/other-tools
> 
> 
> However, none of the mentioned implementations offers the full set of features of Esptool.

should be mentioned that a fairly featureful tool/library exists in rust: https://github.com/esp-rs/espflash

**Comment by bdureau** [comment]
Thanks for your answer
I eventually wrote my own pure java as well as Android implementation
 
DeÂ : Ryan Butler ***@***.*** 
EnvoyÃ©Â : 03 May 2023 11:26
Ã€Â : espressif/esptool
CcÂ : Bear altimeters; Mention
ObjetÂ : Re: [espressif/esptool] How can I upload to ESP32 board via OTG-USB from Android? (ESPTOOL-314) (#665)
 
I'm sorry, this is not supported. I can suggest to search for a solution of running a Python script from Android.
Beside that here is a list of other implementations which could help:
* [esptool-js]( <https://github.com/espressif/esptool-js> https://github.com/espressif/esptool-js) can run from a browser.
 
* There is also a C-based implementation:  <https://github.com/espressif/esp-serial-flasher> https://github.com/espressif/esp-serial-flasher
 
* Rust implementation is under development:  <https://github.com/esp-rs/esp-flash-loader> https://github.com/esp-rs/esp-flash-loader
 
* Windows gui application:  <https://www.espressif.com/en/support/download/other-tools> https://www.espressif.com/en/support/download/other-tools
However, none of the mentioned implementations offers the full set of features of Esptool.
should be mentioned that a fairly featureful tool/library exists in rust:  <https://github.com/esp-rs/espflash> https://github.com/esp-rs/espflash

**Comment by xCarlost** [comment]
Hi @bdureau,
thank you for https://github.com/bdureau/BearConsole2! I tried it and it worked with my esp32dev. Unfortunately, it is not compatible with my esp32-S3. So I have implemented android support in pyserial (the dependency that esptool.py is using to establish serial connection). 
Here is my demo app: https://github.com/xCarlost/FirmwareFlasher
And the pr: https://github.com/pyserial/pyserial/pull/780

**Comment by bdureau** [comment]
hello, I have now fixed it for the ESP32S3 and ESP32C3

**Comment by bdureau** [comment]
> Any update ?

yes if you look at my github I have done all the ESP32 that can work on the Arduino environement

**Comment by gszep** [comment]
Adding fresh hardware findings from an Android/Termux USB-OTG test, since this issue is the closest match.

Setup:
- Android phone running Termux + Termux:API
- ESP32-S2/S3-class Sesame robot firmware device connected by USB OTG
- Device enumerates through `termux-usb -l` as `/dev/bus/usb/001/002`
- USB descriptor: VID:PID `303a:80c2`, CDC ACM-style interfaces, bulk OUT `0x03`, bulk IN `0x84`
- No `/dev/ttyACM*` or `/dev/ttyUSB*` node is exposed on unrooted Android

What works:
- `termux-usb -r` grants raw USB access
- a small C test using `USBDEVFS_CONTROL`/`USBDEVFS_BULK` can send/receive CDC serial bytes to the running firmware
- serial CLI response verified with a firmware `subtrim` command

What does not work yet:
- stock pySerial/esptool cannot flash because there is no POSIX tty device
- pySerial import also failed on Android because `serial.tools.list_ports_posix` raises for `sys.platform == 'android'`; I opened a small pySerial PR to make that enumerator importable/empty: https://github.com/pyserial/pyserial/pull/873

Likely useful path for laptop-free or bridge flashing:
1. implement an Android/Termux USB CDC ACM serial backend that maps Termux's granted USB fd to pySerial-like read/write/control-line operations, or
2. run an RFC2217 serial server on the Android phone that maps DTR/RTS/baud/read/write to the raw CDC ACM device, then run esptool from another machine using `rfc2217://phone:port`, or directly on the phone if packaged.

The RFC2217 bridge route is attractive because esptool already documents remote serial ports and it lets a workstation build firmware while using the phone, reachable over Tailscale/SSH, as the USB bridge to the robot.

**Comment by Dzarda7** [comment]
Hello @gszep, that sounds nice. Thanks for the contribution to the pyserial, but it seems kinda bit as an abandoned project with occasional releases and not really accepting PRs. We are trying to do something about it. But when you already have the necessary part in C, do not want you to use [esp-serial-flasher](https://github.com/espressif/esp-serial-flasher)? Adding support for Android should be as simple as providing part of [these functions](https://github.com/espressif/esp-serial-flasher/blob/master/docs/supporting-new-platform.md#port-operations-vtable).

**Comment by gszep** [comment]
Follow-up from the Android/Termux USB-OTG bridge experiment:

We reached a first successful firmware write through a phone bridge.

Working path:

`calcifer (macOS) -> Tailscale -> Karasu (Android/Termux) -> USB OTG -> ESP32-S2 ROM bootloader`

Key findings:

- Manual BOOT/GPIO0 + RESET was required to enter ROM bootloader. Native USB CDC DTR/RTS from the app device did not by itself provide a reliable bootloader-entry flow.
- Android re-enumerates the device on reset, invalidating the old `termux-usb` fd; the bridge must reopen the new `/dev/bus/usb/...` path and may require another permission grant.
- An RFC2217 bridge using pySerial's `PortManager` works for normal serial and can upload/run the esptool stub after reducing USB bulk OUT chunks to 64 bytes, but RFC2217/telnet escaping was still less robust for larger binary work.
- A raw TCP byte bridge is more reliable once the chip is already in ROM bootloader mode.

Successful smoke writes:

1. Small sector write:
`esptool --no-stub --before no-reset --after no-reset --port socket://100.77.51.88:7777 write-flash 0x3F0000 sector-ff.bin`

2. Full app image write:
`esptool --before no-reset --after no-reset --port socket://100.77.51.88:7777 --chip esp32s2 write-flash 0x10000 sesame-fw.ino.bin`

Result for the app image:
`Wrote 1106832 bytes (697875 compressed) at 0x00010000 in 15.5 seconds (569.8 kbit/s). Hash of data verified.`

Caveat: flashing bootloader/partition table with `--no-stub` hit `Failed to configure SPI flash pins (result was C000: Bad data length)`, but app-only flashing through the raw socket bridge succeeded with the stub already running.

This suggests a pragmatic near-term route for Android-as-field-USB-bridge support: keep build/esptool on the workstation, use the phone as a raw USB CDC socket bridge after manual or firmware-assisted bootloader entry, and later automate re-open after Android USB re-enumeration.

**Comment by gszep** [comment]
@Dzarda7 hi there! I will have a look into your suggestions and submit a PR in relevant location :) - fyi I apologise for the overly verbose comment above

**Comment by Dzarda7** [comment]
Good job @gszep, if having host running is okay for you this is possible. Just beware if you will use RFC2217, pyserial has a bug that causes small communications (typically flash-id) be very slow, https://github.com/pyserial/pyserial/commit/911a0b8c110f3d3513bab67e64d95d1310517454 fixes it, but you know, pyserial release process is unpredictable now.

ESF should be ideal case for you, that way you can get rid of the host simply. Also if you need a feature or change feel free to let me know. At this point we already had a few requests and successful ports to Android, so we can consider merging it into the library directly.

**Comment by gszep** [comment]
Thank you for the tips! Attached is what I'm using it for :) https://github.com/dorianborian/sesame-robot/

https://github.com/user-attachments/assets/8bc89d14-bb9f-43cf-b6a7-c8e28f33c006
