### ISSUE TITLE
ESP32-S3 (Beta3) dev board not supported in espefuse.py  (ESPTOOL-324)

### ISSUE THREAD

**Issue by TGiles1998** [espressif/esptool#674]
# Operating system macOS Mojave 10.14.6

# Python version 2.7.16

# What Chip

ESP32-S3(beta3)

# What development board or other hardware is the chip attached to

ESP32-S3-WROOM-1-N8 DEV BRD

# Is anything else attached to the development board, except for the serial flasher connections?

Nothing 

# Are you running esptool.py from an IDE such as Arduino or Eclipse?

No IDE, Mac OS Terminal

# Full esptool.py command line that was run:

espefuse.py --port /dev/cu.SLAB_USBtoUART summary

# Full output from esptool.py

  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/espefuse.py", line 25, in <module>
    import espressif.efuse.esp32 as esp32_efuse
ImportError: No module named espressif.efuse.esp32

# Do you have any other information from investigating this?

I cannot get esptool.py flash_id to work either

# Is there any other information you can think of which will help us reproduce this problem?

Can you flash something to a ESP32-S3-WROOM-1-N8 DEV BRD

**Comment by radimkarnis** [comment]
Hello @TGiles1998,
how did you install esptool? It seems like some files are missing and Python is therefore having trouble importing them. Please check the [installation instructions](https://github.com/espressif/esptool#installation--dependencies) for more info.

> I cannot get esptool.py flash_id to work either

I will need more information, what command did you run, what was the error output?

Just to be clear: esptool [doesn't fully support ESP32-S3(beta3) in favor of the final S3](https://github.com/espressif/esptool/commit/1ca08afda428ca0abf64096349df5644ead750fb). Connecting beta3 chip will result in a warning, but esptool will try to proceed anyway - only some functions will not work. Your current problem is not a result of using beta3 chip, but of a wrong installation.

**Comment by radimkarnis** [comment]
Great! I am glad your problem got resolved.
Radim
