### ISSUE TITLE
Can't flash ESP32 over RFC2217 with slow IP connection (ESPTOOL-371)

### ISSUE THREAD

**Issue by KlausPopp** [espressif/esptool#704]
My client is in the internet (actually in a gitpod), my server is in the office, so the connection is via internet. The problem appeared when our internet connection had some performance issues.

Running stub...
Traceback (most recent call last):
  File "/opt/esp/idf/components/esptool_py/esptool/esptool.py", line 4535, in <module>
    _main()
  File "/opt/esp/idf/components/esptool_py/esptool/esptool.py", line 4528, in _main
    main()
  File "/opt/esp/idf/components/esptool_py/esptool/esptool.py", line 4046, in main
    esp = esp.run_stub()
  File "/opt/esp/idf/components/esptool_py/esptool/esptool.py", line 793, in run_stub
    p = self.read()
  File "/opt/esp/idf/components/esptool_py/esptool/esptool.py", line 377, in read
    return next(self._slip_reader)
StopIteration
CMake Error at run_serial_tool.cmake:50 (message):

Adding --no-stub solves the problem, however, the programming is then very very slow.

I tracked down the problem and saw that there is a very short timeout of 0.05s applied after esptool.py output `Stub running...`.

This causes problems on slow connections. I worked around it as follows:

`esp/idf/components/esptool_py/esptool/esptool.py`:

```
    def command(self, op=None, data=b"", chk=0, wait_response=True, timeout=DEFAULT_TIMEOUT):
        saved_timeout = self._port.timeout
        new_timeout = min(timeout, MAX_TIMEOUT)
 added>>>       new_timeout = max(timeout, 1)

```
Could you add this fix in the code please?

_Originally posted by @KlausPopp in https://github.com/espressif/esptool/issues/628#issuecomment-986777466_

**Comment by radimkarnis** [comment]
Hello @KlausPopp,

thank you for investigating this! 

Adding this line of code would maybe solve the issue for your particular use case and environment, but would limit all the other commands for all esptool users to have a minimum timeout of 1 second. I am sorry, but this is not a viable solution.

In your case, I think it would be more appropriate to increase the [MEM_END_ROM_TIMEOUT](https://github.com/espressif/esptool/blob/master/esptool.py#L73) value. If you ever encounter the mentioned network performance issues again, can you please try this out?

We are contemplating adding a configuration option to esptool to allow users to edit these timeouts to suit their particular use case. This would allow more flexibility without the need of adding code fixes like this one.

Will close this issue for now. Feel free to reopen if you think further discussion is needed.

Radim
