### ISSUE TITLE
windows 11 not detecting (ESPTOOL-375)

### ISSUE THREAD

**Issue by settlelol** [espressif/esptool#707]
### Operating System

Windows 11

### Version

v3.2

### Python Version

Python 3.9.7

### Chip Description

ESP8226

### Device Description

[aliexpress link](https://www.aliexpress.com/item/1005001952641270.html)

### How is Esptool Run

Latest version of n2d [https://github.com/a4004/n2d]

### Other Steps to Reproduce

I have the Silabs driver and I have installed the CH340 driver although it doesnt appear on the device manager port section for some reason

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by dobairoland** [comment]
Hi @settlelol. Please try with the drivers posted in https://github.com/espressif/esptool/issues/706.

**Comment by settlelol** [comment]
https://i.imgur.com/WCRnGZR.png

i get this when trying to install it

**Comment by settlelol** [comment]
> Hi @settlelol. Please try with the drivers posted in #706.

https://i.imgur.com/WCRnGZR.png

i get this when trying to install it

**Comment by radimkarnis** [comment]
Closing this issue. Feel free to reopen if you think further discussion is needed.
