### ISSUE TITLE
Failed to create process (ESPTOOL-384)

### ISSUE THREAD

**Issue by kingnoss** [espressif/esptool#713]
### Operating System

Windows

### Version

latest master

### Python Version

Python 3.10.1

### Full Esptool Command Line that Was Run

esptool.py version

### Esptool Output

```shell
failed to create process
```

### What is the Expected Behaviour?

Print version number

### More Information

I have tried removing esptool , as well as pip, even removing Python it's self. would the python version affect esptool?

### Other Steps to Reproduce

no

**Comment by dobairoland** [comment]
So you want to run esptool directly without installing it?

Please try `python .\esptool.py version` from the cloned repo. Probably you will need to install package dependencies for `python`, so I really don't recommend to go this way.

The recommended way to install: https://docs.espressif.com/projects/esptool/en/latest/esp32/installation.html

The development setup can be used to install the latest master version: https://docs.espressif.com/projects/esptool/en/latest/esp32/contributing.html#development-setup

The `failed to create process` is a Windows error and not esptool.
