### ISSUE TITLE
Request for 3.2.1 or 3.3 release soon (ESPTOOL-393)

### ISSUE THREAD

**Issue by dhalbert** [espressif/esptool#715]
### Is your feature request related to a problem?

https://github.com/espressif/esptool/issues/685 (and similar issues) report a problem with automated chip detection, which was fixed, but has not yet been released. A number of users are being caught by this problem.

### Describe the solution you'd like

A bugfix release 3.2.1 or an accelerated 3.3 release would be helpful.

### Describe alternatives you've considered

Rolling back to v3.1 or cautioning users against automated detection.

**Comment by radimkarnis** [comment]
Hello @dhalbert,
understandable, we'll try to do our best.

Btw, is advising users to use the latest master branch not a viable solution? I am asking because it usually takes some time until a new esptool version propagates into all frameworks (Arduino, PIO, ...)
