### ISSUE TITLE
S3 Flash / PSRAM type (QIO / OPI) detection commands (ESPTOOL-435)

### ISSUE THREAD

**Issue by Jason2866** [espressif/esptool#730]
### Is your feature request related to a problem?

Since S3 introduced a new Flash type (OPI) it is mandantory to flash the correct
combination of used Flash / PSRAM type bootloader/ firmware. Without the device does fail to boot.
It is a problem for the user to know which flash mode has to be used for Flash / PSRAM.
Since there are many different variants already to get, and it is not possible to identify the used chips and there modes. 

### Describe the solution you'd like

A command which prints out the supported flash type for S3 for flash and PSRAM

### Describe alternatives you've considered

Guessing and trying all variants until S3 is booting.

### Additional context

See disscussion [here](https://github.com/espressif/arduino-esp32/pull/6450#discussion_r833119694)

**Comment by radimkarnis** [comment]
Hello @Jason2866, thank you for the feature request.

We will look into this! Currently, I can't promise this to be done in any specific timeframe, though.

**Comment by squix78** [comment]
+1, please add support for opi flash

**Comment by arendst** [comment]
+1, please add support for opi flash.

Enhances Tasmota user experience a lot.

**Comment by egnor** [comment]
Would it be possible to clarify this bug report? Is it a documentation bug or a functionality bug? What would the better documentation look like? What _are_ the correct flash modes to use? Does "S3" here refer to the ESP32-S3?

**Comment by Jason2866** [comment]
@egnor It is not a bug report it is a feature request for the ESP32-S3 for a command which identifies the type of flash/psram and prints this out.

**Comment by dobairoland** [comment]
The `flash_id` command has been extended with information about the flash type. We have not added a separate command for this. If needed, the required information can be obtained from the eFuse as it was done in https://github.com/espressif/esptool/commit/b25606b95920bd06df87aff9202c7a15377d4a30.

Implementing the PSRAM part is not possible at the moment. Please see the linked ESP-IDF request.

**Comment by Jason2866** [comment]
Thanks!
