### ISSUE TITLE
Update Boot Mode Selection page to cover all new chips (ESPTOOL-438)

### ISSUE THREAD

**Issue by lonerzzz** [espressif/esptool#732]
### Is your feature request related to a problem?

While working through an issue with a custom board not getting into the correct boot mode, I was unable to find documentation indicating what I should be expecting on the terminal output. In the assistance I received, I was directed to this page:

https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/boot-mode-selection.html#boot-log

Currently, this page does not exist for the ESP32 C3 and other similar boards so it was not easy to find.

### Describe the solution you'd like

The page mentioned above should be replicated for all new chips to make it easier to find and to ensure that it is understood to be relevant to the chip being used.

**Comment by radimkarnis** [comment]
Hi @lonerzzz,

thank you for the feature request. 
I am just going to link our previous discussion and context: https://github.com/espressif/esptool/issues/731.
