### ISSUE TITLE
esptool.py doesn't correctly detect integrated USB bootloader on ESP32-S3 (ESPTOOL-484)

### ISSUE THREAD

**Issue by egnor** [espressif/esptool#756]
### Operating System

(all known)

### Esptool Version

v4.1-16-g762e381

### Python Version

python 3.10.4

### Chip Description

ESP32-S3

### Device Description

Adafruit Feather ESP32-S3 TFT
(but I believe this will apply to all ESP32-S3 boards)

### How is Esptool Run

from any environment

### Full Esptool Command Line that Was Run

esptool.py -p /dev/ttyXXX read_mac  # or anything

### Esptool Output

```shell
Normal output is generally normal:


% esptool.py -p /dev/ttyACM0 read_mac
esptool.py v4.1
Serial port /dev/ttyACM0
Connecting....
Detecting chip type... ESP32-S3
Chip is ESP32-S3
Features: WiFi, BLE
Crystal is 40MHz
MAC: f4:12:fa:59:69:84
Uploading stub...
Running stub...
Stub running...
MAC: f4:12:fa:59:69:84
Hard resetting via RTS pin...
```

However, in `esptool.py`, `self.uses_usb()` is returning false in this mode. The [implementation of `uses_usb()`](https://github.com/espressif/esptool/blob/65f861420515217f7b5d209fce288808dc5b1943/esptool/targets/esp32s3.py#L161) checks a magic value in the ROM's data segment (`UARTDEV_BUF_NO = 0x3FCEF14C`) to see if it indicates USB loading (`UARTDEV_BUF_NO_USB = 3`). However in my experiments this value is 4, not 3. This is for example why `_check_if_can_reset()` (checking for GPIO0 forced-bootloader mode that prevents resetting, I think?) isn't working as expected on the ESP32-S3.
```


### More Information

_No response_

### Other Steps to Reproduce

_No response_

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by radimkarnis** [comment]
Hello @egnor,

as I explained in the PR, `uses_usb()` is meant to check for the USB-OTG mode and has nothing to do with the USB-Serial/JTAG mode. `_check_if_can_reset()` is supposed to run only in USB-OTG mode.
