### ISSUE TITLE
Inconsistency of bit position reading pkg_version from ESP32-C2 (ESPTOOL-487)

### ISSUE THREAD

**Issue by xingrz** [espressif/esptool#759]
### Operating System

macOS 12.4

### Esptool Version

v4.1-15-g65f8614

### Python Version

Python 3.9.13

### Chip Description

ESP32-C2

### Device Description

ESP8684-DevKitM-1

### How is Esptool Run

Terminal (iTerm.app)

### Full Esptool Command Line that Was Run

esptool.py --port /dev/cu.usbserial-14110 flash_id

### Esptool Output

```shell
esptool.py v3.3.1
Serial port /dev/cu.usbserial-14110
Connecting....
Detecting chip type... ESP32-C2
Chip is ESP32-C2 (revision 1)
Features: Wi-Fi
Crystal is 40MHz
MAC: 10:97:bd:f1:e6:3c
Uploading stub...
Running stub...
Stub running...
Manufacturer: 5e
Device: 4016
Detected flash size: 4MB
Hard resetting via RTS pin...
```

### More Information

`esptool.py` works well, actually. But after reviewing the code, I found something inconsistent.

According to [esp_efuse_table.csv#L69](https://github.com/espressif/esp-idf/blob/9b8c558e63d95b491355a22e69f247834e899b47/components/efuse/esp32c2/esp_efuse_table.csv#L69) in ESP-IDF, the position of `PKG_VERSION` is at bit `54` of `EFUSE_BLK2` (which is also `EFUSE_RD_BLK2_DATA0_REG`).

As we learn from [efuse_reg.h#L312](https://github.com/espressif/esp-idf/blob/9b8c558e63d95b491355a22e69f247834e899b47/components/soc/esp32c2/include/soc/efuse_reg.h#L312), the value of `EFUSE_RD_BLK2_DATA0_REG` is `DR_REG_EFUSE_BASE + 0x40` and `EFUSE_RD_BLK2_DATA1_REG` is `DR_REG_EFUSE_BASE + 0x44`. So we can infer that the bit position of `PKG_VERSION` counting from `0x044` should be `22`.

While in [esp32c2.py#L55](https://github.com/espressif/esptool/blob/65f861420515217f7b5d209fce288808dc5b1943/esptool/targets/esp32c2.py#L55), we read the forth word (`EFUSE_BASE + 0x044` plus 12 bytes) and right shifted 21 bits (considering the byte order, means moving the pointer right 21 bits). This is actually `12 bytes + 21 bits = 117 bits` counting from `0x044`, or bit `149` counting from `EFUSE_BLK2`.

https://github.com/espressif/esptool/blob/65f861420515217f7b5d209fce288808dc5b1943/esptool/targets/esp32c2.py#L52-L55

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by dobairoland** [comment]
Thank you for your report!
