### ISSUE TITLE
Could you include MANIFEST.in in sdist? (ESPTOOL-498)

### ISSUE THREAD

**Issue by befeleme** [espressif/esptool#767]
### Operating System

Fedora Linux 35-37

### Esptool Version

4.2.1

### Python Version

Python 3.10/3.11

### What is the Expected Behaviour?

Hello,
the MANIFEST.in is not currently included in the sdist: https://github.com/espressif/esptool/blob/master/MANIFEST.in#L11
This is not a problem when building wheel from sdist directly. 
In Fedora, where we package esptool as RPM, this causes a failure to build wheel that includes the JSON stubs.
The issue is that we regenerate metadata before building the wheel (we call `setuptools.build_meta.prepare_metadata_for_build_wheel(".")`), which means the folder `egg-info/` where the information about JSON files is stored, is deleted. The wheel is then built with the fresh dist-info which - at this point - have nowhere defined that is should include the JSON files too.
It's common for projects that define MANIFEST.in to include it into sdist. We've checked this will solve our issue too.

**Comment by radimkarnis** [comment]
Hello @befeleme,

thanks for the detailed report and proposed solution! 
I will fix this ASAP.
