### ISSUE TITLE
Win32 prebuilt package on conda-forge contains invalid path in .exe file (ESPTOOL-504)

### ISSUE THREAD

**Issue by wesley800** [espressif/esptool#772]
### Operating System

Windows 10

### Esptool Version

v4.2.1

### Python Version

python 3.8

### Full Esptool Command Line that Was Run

C:\Anaconda3\Scripts\esptool.exe

### Esptool Output

```shell
Fatal error in launcher: Unable to create process using '"D:\bld\esptool_1660073556864\_h_env\python.exe"  "C:\Anaconda3\Scripts\esptool.exe" ': The system cannot find the file specified.
```

### More Information

The string `D:\bld\esptool_1660073556864\_h_env\python.exe` lies in all `.exe`s in the prebuilt package, except those `.py.exe`s.

**Comment by radimkarnis** [comment]
Hi @wesley800,

this is not an esptool issue and should be discussed elsewhere - probably in the [conda-forge/esptool-feedstock](https://github.com/conda-forge/esptool-feedstock/) repository.

There seems to be a ticket discussing the same issue: https://github.com/conda-forge/esptool-feedstock/issues/12

Please follow it there, thank you!
