### ISSUE TITLE
win11 'esptool.py' is not recognized as an internal or external command, operable program or batch file. (ESPTOOL-515)

### ISSUE THREAD

**Issue by spikey1973** [espressif/esptool#777]
### Operating System

win11 

### Esptool Version

v4.2.1

### Python Version

Python 3.10

### Full Esptool Command Line that Was Run

esptool.py -h

### Esptool Output

```shell
'esptool.py' is not recognized as an internal or external command,
operable program or batch file.
```

### What is the Expected Behaviour?

help function 

### More Information

ran: pip3 install esptool: 

# requirements already satisfied

Requirement already satisfied: esptool in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (4.2.1)
Requirement already satisfied: bitstring>=3.1.6 in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from esptool) (3.1.9)
Requirement already satisfied: cryptography>=2.1.4 in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from esptool) (37.0.4)
Requirement already satisfied: ecdsa>=0.16.0 in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from esptool) (0.18.0)
Requirement already satisfied: pyserial>=3.0 in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from esptool) (3.5)
Requirement already satisfied: reedsolo<=1.5.4,>=1.5.3 in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from esptool) (1.5.4)
Requirement already satisfied: cffi>=1.12 in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cryptography>=2.1.4->esptool) (1.15.1)
Requirement already satisfied: six>=1.9.0 in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from ecdsa>=0.16.0->esptool) (1.16.0)
Requirement already satisfied: pycparser in c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cffi>=1.12->cryptography>=2.1.4->esptool) (2.21)

ran:  pip show -f esptool: 

# couldn't find /bin/esptool.py

Name: esptool
Version: 4.2.1
Summary: A serial utility to communicate & flash code to Espressif chips.
Home-page: https://github.com/espressif/esptool/
Author: Fredrik Ahlberg (themadinventor) & Angus Gratton (projectgus) & Espressif Systems
Author-email:
License: GPLv2+
Location: c:\users\mvkin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
Requires: bitstring, cryptography, ecdsa, pyserial, reedsolo
Required-by:
Files:
  ..\Scripts\espefuse.py-script.py
  ..\Scripts\espefuse.py.exe
  ..\Scripts\espsecure.py-script.py
  ..\Scripts\espsecure.py.exe
  ..\Scripts\esptool.py-script.py
  ..\Scripts\esptool.py.exe
  espefuse\__init__.py
  espefuse\__main__.py
  espefuse\__pycache__\__init__.cpython-310.pyc
  espefuse\__pycache__\__main__.cpython-310.pyc
  espefuse\efuse\__init__.py
  espefuse\efuse\__pycache__\__init__.cpython-310.pyc
  espefuse\efuse\__pycache__\base_fields.cpython-310.pyc
  espefuse\efuse\__pycache__\base_operations.cpython-310.pyc
  espefuse\efuse\__pycache__\emulate_efuse_controller_base.cpython-310.pyc
  espefuse\efuse\__pycache__\mem_definition_base.cpython-310.pyc
  espefuse\efuse\__pycache__\util.cpython-310.pyc
  espefuse\efuse\base_fields.py
  espefuse\efuse\base_operations.py
  espefuse\efuse\emulate_efuse_controller_base.py
  espefuse\efuse\esp32\__init__.py
  espefuse\efuse\esp32\__pycache__\__init__.cpython-310.pyc
  espefuse\efuse\esp32\__pycache__\emulate_efuse_controller.cpython-310.pyc
  espefuse\efuse\esp32\__pycache__\fields.cpython-310.pyc
  espefuse\efuse\esp32\__pycache__\mem_definition.cpython-310.pyc
  espefuse\efuse\esp32\__pycache__\operations.cpython-310.pyc
  espefuse\efuse\esp32\emulate_efuse_controller.py
  espefuse\efuse\esp32\fields.py
  espefuse\efuse\esp32\mem_definition.py
  espefuse\efuse\esp32\operations.py
  espefuse\efuse\esp32c2\__init__.py
  espefuse\efuse\esp32c2\__pycache__\__init__.cpython-310.pyc
  espefuse\efuse\esp32c2\__pycache__\emulate_efuse_controller.cpython-310.pyc
  espefuse\efuse\esp32c2\__pycache__\fields.cpython-310.pyc
  espefuse\efuse\esp32c2\__pycache__\mem_definition.cpython-310.pyc
  espefuse\efuse\esp32c2\__pycache__\operations.cpython-310.pyc
  espefuse\efuse\esp32c2\emulate_efuse_controller.py
  espefuse\efuse\esp32c2\fields.py
  espefuse\efuse\esp32c2\mem_definition.py
  espefuse\efuse\esp32c2\operations.py
  espefuse\efuse\esp32c3\__init__.py
  espefuse\efuse\esp32c3\__pycache__\__init__.cpython-310.pyc
  espefuse\efuse\esp32c3\__pycache__\emulate_efuse_controller.cpython-310.pyc
  espefuse\efuse\esp32c3\__pycache__\fields.cpython-310.pyc
  espefuse\efuse\esp32c3\__pycache__\mem_definition.cpython-310.pyc
  espefuse\efuse\esp32c3\__pycache__\operations.cpython-310.pyc
  espefuse\efuse\esp32c3\emulate_efuse_controller.py
  espefuse\efuse\esp32c3\fields.py
  espefuse\efuse\esp32c3\mem_definition.py
  espefuse\efuse\esp32c3\operations.py
  espefuse\efuse\esp32h2beta1\__init__.py
  espefuse\efuse\esp32h2beta1\__pycache__\__init__.cpython-310.pyc
  espefuse\efuse\esp32h2beta1\__pycache__\emulate_efuse_controller.cpython-310.pyc
  espefuse\efuse\esp32h2beta1\__pycache__\fields.cpython-310.pyc
  espefuse\efuse\esp32h2beta1\__pycache__\mem_definition.cpython-310.pyc
  espefuse\efuse\esp32h2beta1\__pycache__\operations.cpython-310.pyc
  espefuse\efuse\esp32h2beta1\emulate_efuse_controller.py
  espefuse\efuse\esp32h2beta1\fields.py
  espefuse\efuse\esp32h2beta1\mem_definition.py
  espefuse\efuse\esp32h2beta1\operations.py
  espefuse\efuse\esp32s2\__init__.py
  espefuse\efuse\esp32s2\__pycache__\__init__.cpython-310.pyc
  espefuse\efuse\esp32s2\__pycache__\emulate_efuse_controller.cpython-310.pyc
  espefuse\efuse\esp32s2\__pycache__\fields.cpython-310.pyc
  espefuse\efuse\esp32s2\__pycache__\mem_definition.cpython-310.pyc
  espefuse\efuse\esp32s2\__pycache__\operations.cpython-310.pyc
  espefuse\efuse\esp32s2\emulate_efuse_controller.py
  espefuse\efuse\esp32s2\fields.py
  espefuse\efuse\esp32s2\mem_definition.py
  espefuse\efuse\esp32s2\operations.py
  espefuse\efuse\esp32s3\__init__.py
  espefuse\efuse\esp32s3\__pycache__\__init__.cpython-310.pyc
  espefuse\efuse\esp32s3\__pycache__\emulate_efuse_controller.cpython-310.pyc
  espefuse\efuse\esp32s3\__pycache__\fields.cpython-310.pyc
  espefuse\efuse\esp32s3\__pycache__\mem_definition.cpython-310.pyc
  espefuse\efuse\esp32s3\__pycache__\operations.cpython-310.pyc
  espefuse\efuse\esp32s3\emulate_efuse_controller.py
  espefuse\efuse\esp32s3\fields.py
  espefuse\efuse\esp32s3\mem_definition.py
  espefuse\efuse\esp32s3\operations.py
  espefuse\efuse\esp32s3beta2\__init__.py
  espefuse\efuse\esp32s3beta2\__pycache__\__init__.cpython-310.pyc
  espefuse\efuse\esp32s3beta2\__pycache__\emulate_efuse_controller.cpython-310.pyc
  espefuse\efuse\esp32s3beta2\__pycache__\fields.cpython-310.pyc
  espefuse\efuse\esp32s3beta2\__pycache__\mem_definition.cpython-310.pyc
  espefuse\efuse\esp32s3beta2\__pycache__\operations.cpython-310.pyc
  espefuse\efuse\esp32s3beta2\emulate_efuse_controller.py
  espefuse\efuse\esp32s3beta2\fields.py
  espefuse\efuse\esp32s3beta2\mem_definition.py
  espefuse\efuse\esp32s3beta2\operations.py
  espefuse\efuse\mem_definition_base.py
  espefuse\efuse\util.py
  espsecure\__init__.py
  espsecure\__main__.py
  espsecure\__pycache__\__init__.cpython-310.pyc
  espsecure\__pycache__\__main__.cpython-310.pyc
  esptool-4.2.1-py3.10.egg-info\PKG-INFO
  esptool-4.2.1-py3.10.egg-info\SOURCES.txt
  esptool-4.2.1-py3.10.egg-info\dependency_links.txt
  esptool-4.2.1-py3.10.egg-info\entry_points.txt
  esptool-4.2.1-py3.10.egg-info\requires.txt
  esptool-4.2.1-py3.10.egg-info\top_level.txt
  esptool\__init__.py
  esptool\__main__.py
  esptool\__pycache__\__init__.cpython-310.pyc
  esptool\__pycache__\__main__.cpython-310.pyc
  esptool\__pycache__\bin_image.cpython-310.pyc
  esptool\__pycache__\cmds.cpython-310.pyc
  esptool\__pycache__\loader.cpython-310.pyc
  esptool\__pycache__\util.cpython-310.pyc
  esptool\bin_image.py
  esptool\cmds.py
  esptool\loader.py
  esptool\targets\__init__.py
  esptool\targets\__pycache__\__init__.cpython-310.pyc
  esptool\targets\__pycache__\esp32.cpython-310.pyc
  esptool\targets\__pycache__\esp32c2.cpython-310.pyc
  esptool\targets\__pycache__\esp32c3.cpython-310.pyc
  esptool\targets\__pycache__\esp32c6beta.cpython-310.pyc
  esptool\targets\__pycache__\esp32h2beta1.cpython-310.pyc
  esptool\targets\__pycache__\esp32h2beta2.cpython-310.pyc
  esptool\targets\__pycache__\esp32s2.cpython-310.pyc
  esptool\targets\__pycache__\esp32s3.cpython-310.pyc
  esptool\targets\__pycache__\esp32s3beta2.cpython-310.pyc
  esptool\targets\__pycache__\esp8266.cpython-310.pyc
  esptool\targets\esp32.py
  esptool\targets\esp32c2.py
  esptool\targets\esp32c3.py
  esptool\targets\esp32c6beta.py
  esptool\targets\esp32h2beta1.py
  esptool\targets\esp32h2beta2.py
  esptool\targets\esp32s2.py
  esptool\targets\esp32s3.py
  esptool\targets\esp32s3beta2.py
  esptool\targets\esp8266.py
  esptool\targets\stub_flasher\stub_flasher_32.json
  esptool\targets\stub_flasher\stub_flasher_32c2.json
  esptool\targets\stub_flasher\stub_flasher_32c3.json
  esptool\targets\stub_flasher\stub_flasher_32c6beta.json
  esptool\targets\stub_flasher\stub_flasher_32h2beta1.json
  esptool\targets\stub_flasher\stub_flasher_32h2beta2.json
  esptool\targets\stub_flasher\stub_flasher_32s2.json
  esptool\targets\stub_flasher\stub_flasher_32s3.json
  esptool\targets\stub_flasher\stub_flasher_32s3beta2.json
  esptool\targets\stub_flasher\stub_flasher_8266.json
  esptool\util.py

Googled the error msg: 

# It was found, but none of the proposed answers i found worked for me. 

I looked in the local folder .../site-packages/esptool:

# did not find eptool.py

28/08/2022  21:32    <DIR>          .
28/08/2022  21:34    <DIR>          ..
09/08/2022  18:00            44.667 bin_image.py
09/08/2022  18:00            39.092 cmds.py
09/08/2022  18:00            56.604 loader.py
28/08/2022  21:32    <DIR>          targets
09/08/2022  18:00             4.318 util.py
09/08/2022  18:00            33.658 __init__.py
09/08/2022  18:00               270 __main__.py
28/08/2022  21:32    <DIR>          __pycache__
               6 File(s)        178.609 bytes
               4 Dir(s)  732.253.667.328 bytes free

### Other Steps to Reproduce

run any esptool command

**Comment by radimkarnis** [comment]
Hello @spikey1973,

thanks for reporting this. Just to check - can you run the command without the `.py` extension (e.g. `esptool flash_id`)?

**Comment by spikey1973** [comment]
Hello, 

just to double check i ran the command but no esptool command with or without .py works. 

Kind greats 

Matthieiu

**Comment by radimkarnis** [comment]
Can you run other python modules this way (install with pip -> run on a command line)?

This seems like a $PATH problem in your shell - $PATH being the environment variable that controls how (and where) your shell is able to locate and invoke commands like `epstool.py` (the command line tool). You need to fix your $PATH. On Windows, you have to locate the `esptool.py` executable and add the enclosing folder to your $PATH, then restart all of your shells (so the updated environment variable can take effect.) In fact, pip probably told you you had to do this when you installed the tool - it's usually pretty aware of when it installs a command line tool but isn't able to put it on your path for you.

Another thing to try is to invoke esptool as: `python -m esptool` (or `python3 -m esptool`)

**Comment by radimkarnis** [comment]
I am closing this issue, it has been answered and it seems like it's not relevant anymore. Feel free to reopen if necessary!

**Comment by webwarrior** [comment]
I had to download the esptool from github, and then run the command, even when it was installed by pip install:
C:\Dev\esp32\esptool\esptool --chip esp32 --port COMx erase_flash
