### ISSUE TITLE
Faster CPU clock speed in stub flasher for higher performance (ESPTOOL-519)

### ISSUE THREAD

**Issue by Emill** [espressif/esptool#779]
### Is your feature request related to a problem?

I'm mainly programming for ESP32-S3 with the built-in serial usb functionality.

The esptool.py flash performance is quite slow compared to the ideal when considering the USB speed and the erase/programming time for the flash.

A project I built flashes in 746 kbit/s.

### Describe the solution you'd like

I then modified the stub flasher initialisation in the following way:

1. Set SYSTEM_CPUPERIOD_SEL to 2.
2. Set SYSTEM_SOC_CLK_SEL to 1.

This sets the CPU frequency to 240 MHz instead of the default 20 MHz.

Now the project flashes at an average speed of 1405 kbit/s.

Hash verify time is also much faster.

Total time goes from 34 seconds to 16 seconds.

Have you considered increasing the cpu frequency in esptool, to speed up the flashing performance?

**Comment by radimkarnis** [comment]
Hi @Emill,

Thanks for bringing this up, that's an interesting idea! 

You explain you have a working implementation of this, would you be willing to send a pull request? We can explore this idea more.
