### ISSUE TITLE
Documentation error for FLASH_BEGIN command (ESPTOOL-522)

### ISSUE THREAD

**Issue by dc42** [espressif/esptool#782]
### Operating System

Not relevant

### Esptool Version

Not relevant

### Python Version

Not relevant

### Full Esptool Command Line that Was Run

Not relevant

### Esptool Output

```shell
Not relevant
```

### What is the Expected Behaviour?

Not relevant

### More Information

The documentation at https://github.com/espressif/esptool/blob/master/docs/en/advanced-topics/serial-protocol.rst says that the FLASH_BEGIN command takes four 32-bit parameters. This is correct for the ESP8266 but incorrect for at least the ESP32C3 and ESP32S3. If I send four 32-bit parameters with this command, the ROM bootloader returns error 0x05. Examining the esptool code I saw that esptool adds a fifth 32-bit word to this command for ESP variant that support flash encryption, which is 0 if flash encryption is not used. I added this fifth parameter to my upload code and it now works.

**Comment by radimkarnis** [comment]
Hi @dc42,

thanks for noticing. I will update the docs ASAP!
