### ISSUE TITLE
keyfile pem as String and not as file path (ESPTOOL-526)

### ISSUE THREAD

**Issue by caniot** [espressif/esptool#786]
### Is your feature request related to a problem?

espsecure.py is great tool , but the keyfile is only passed as file path to sign_data, it will be great to pass the key also as string , in this case we can sign bin file without having the keyfile locally.

**Comment by dobairoland** [comment]
There is a security implication for implementing this which I think not everyone would realize and can become easily a victim. The shell would save the key into the history of run commands.
