### ISSUE TITLE
espsecure.py fails with error "ecdsa.der.UnexpectedDER: wanted type 'object' (0x06), got 0x05" (ESPTOOL-529)

### ISSUE THREAD

**Issue by mbratch** [espressif/esptool#789]
### Operating System

WIndows 10

### Esptool Version

v3.3.2-dev

### Python Version

3.8.7

### Full Esptool Command Line that Was Run

python .../components/esptool_py/esptool/espsecure.py sign_data --keyfile ca_key.pem --version 1  .../build/my-proj.bin

### Esptool Output

(NOTE I used "..." to denote private parts of the path)

```shell
python C:/.../.espressif/frameworks/esp-idf-v4.4.2/components/esptool_py/esptool/espsecure.py sign_data --keyfile ca_key.pem --version 1                 C:/.../build/BD-OTB.bin
espsecure.py v3.3.2-dev
Traceback (most recent call last):
  File "C:/.../.espressif/frameworks/esp-idf-v4.4.2/components/esptool_py/esptool/espsecure.py", line 1145, in <module>
    _main()
  File "C:/.../.espressif/frameworks/esp-idf-v4.4.2/components/esptool_py/esptool/espsecure.py", line 1138, in _main
    main()
  File "C:/.../.espressif/frameworks/esp-idf-v4.4.2/components/esptool_py/esptool/espsecure.py", line 1128, in main
    operation_func(args)
  File "C:/.../.espressif/frameworks/esp-idf-v4.4.2/components/esptool_py/esptool/espsecure.py", line 281, in sign_data
    return sign_secure_boot_v1(args)
  File "C:/.../.espressif/frameworks/esp-idf-v4.4.2/components/esptool_py/esptool/espsecure.py", line 290, in sign_secure_boot_v1
    sk = _load_ecdsa_signing_key(args.keyfile[0])
  File "C:/.../.espressif/frameworks/esp-idf-v4.4.2/components/esptool_py/esptool/espsecure.py", line 201, in _load_ecdsa_signing_key
    sk = ecdsa.SigningKey.from_pem(keyfile.read())
  File "C:\...\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\ecdsa\keys.py", line 927, in from_pem
    return cls.from_der(
  File "C:\...\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\ecdsa\keys.py", line 1017, in from_der
    curve = Curve.from_der(algorithm_identifier, valid_curve_encodings)
  File "C:\...\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\ecdsa\curves.py", line 165, in from_der
    oid, empty = der.remove_object(data)
  File "C:\...\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\ecdsa\der.py", line 175, in remove_object
    raise UnexpectedDER("wanted type 'object' (0x06), got 0x%02x" % n)
ecdsa.der.UnexpectedDER: wanted type 'object' (0x06), got 0x05
```
Sample program attached.

[EspSecTest.zip](https://github.com/espressif/esptool/files/9825048/EspSecTest.zip)

### What is the Expected Behavior?

Successful signing of the application file with the given security key without generating an error.

### More Information

I'm using ESP-IDF 4.4.2

**Comment by radimkarnis** [comment]
Hello @mbratch,
thanks for the report!

Does this also happen with the latest version of espsecure.py? 

Can you provide a minimal example so we can try to reproduce this? 

Thank you.

**Comment by mbratch** [comment]
@radimkarnis I noticed there are two different `espsecure.py` tool files. One is installed with my ESP-IDF v4.4.2 under components/esptool_py/esptool. This is the "official" version with v4.4.2 from what I can tell, and is the tool that is called when the build process runs.

I noticed on github that there is a whole separate area called `espressif/esptool` which also has `espsecure.py`. I don't know if this is the same or different. I noticed the tool version is "about" the same. That is, `espressif/esptool` latest version is stated as 3.3.2, and my esp tools report as 3.3.2-dev.

Also `espsecure.py` is a fairly brief script. It calls on other scripts to do the work. I apologize I didn't provide the full traceback, so I updated my issue to include that. Let me know from there what else you may need.

**Comment by radimkarnis** [comment]
Hi @mbratch,

ESP-IDF v4.4.2 actually uses this repository as a submodule under the hood, so the `espsecure.py` tool is actually the same thing as here (just an older version! we are on [version v4.3](https://github.com/espressif/esptool/releases/tag/v4.3) in this repository). You can see the [installation instructions here](https://docs.espressif.com/projects/esptool/en/latest/esp32/installation.html). 

After inspecting the provided trace, it seems like the error comes from the `ecdsa` module used by `espsecure.py`. I tried with `espsecure.py` v4.4-dev and can reproduce the issue. I will try to debug more and see if this is a problem with `espsecure.py`, `ecdsa` or the keyfile.

**Comment by radimkarnis** [comment]
If I remove the `espsecure.py` logic and try to isolate the problem, it all boils down to this:

```python
import ecdsa

with open("ca_key.pem") as keyfile:
    ecdsa.SigningKey.from_pem(keyfile.read())
```

If we run this, we get the same error. So it is definitely `ecdsa` having troubles with the key file you provided. Can you please try a different key (maybe using a different curve?).

**Comment by mbratch** [comment]
@radimkarnis thank you very much for investigating.
Here's the command I used to generate the key/cert:
`openssl req -x509 -newkey rsa:2048 -keyout ca_key.pem -out ca_cert.pem -days 365 -nodes`
I found this on some website somewhere and it was pertaining to ESP32.

I'm not sure how to change the "curve" on this command, but after some searching, I found this AWS site which gives a different set of options to generate a key and certificate:
https://docs.aws.amazon.com/freertos/latest/userguide/ota-code-sign-cert-esp.html

I tried that and it seems to work.

I was half expecting the Espressif documentation to give at least one working example of how to generate a compatible key/cert pair. :)

**Comment by radimkarnis** [comment]
Ok, I'm glad you managed to make it work!

> I guess I was half expecting the Espressif documentation to give at least one working example of how to generate a compatible key/cert pair. :)

Our documentation actually mentions that [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v2.html#generating-secure-boot-signing-key) or [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v2.html#how-to-enable-secure-boot-v2). It's also possible to run `espsecure.py -h` and you'll see info about the `generate_flash_encryption_key` and `generate_signing_key` commands.

Can we consider this issue as solved and close it?

**Comment by mbratch** [comment]
> Our documentation actually mentions that [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v2.html#generating-secure-boot-signing-key) or [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v2.html#how-to-enable-secure-boot-v2). It's also possible to run `espsecure.py -h` and you'll see info about the `generate_flash_encryption_key` and `generate_signing_key` commands.
> 
Oh my.... I searched a lot and didn't spot that. Thank you!

> Can we consider this issue as solved and close it?

Yes!
