### ISSUE TITLE
d1mini flash  (ESPTOOL-579)

### ISSUE THREAD

**Issue by dl6dbh** [espressif/esptool#815]
### Operating System

linux 

### Esptool Version

esptool.py 2.8

### Python Version

python 2.7.18

### Chip Description

esp d1 mini 

### How is Esptool Run

arduino 

### Full Esptool Command Line that Was Run

esptool --port /dev/ttyUSB0 write_flash  --flash_mode qio  0x00000 ./0x00000.bin  0x02000 ./0x02000.bin

### Esptool Output

```shell
i fash an d1 mini with following
esptool --port /dev/ttyUSB0 write_flash  --flash_mode qio  0x00000 ./0x00000.bin  0x02000 ./0x02000.bin

 - no error 
 - on serial monitor i see the wifi repeter start 
 - but i can't see an ap
```

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by dobairoland** [comment]
Please, you cannot blame the flasher issues with your application. I'm sorry but we cannot help with this.

I can suggest to you to observe the serial output - it looks like you already do this - and figure out the issue with the application based on that. You can debug your application or add more logs.
