### ISSUE TITLE
esptool.py install from Pypi (ESPTOOL-611)

### ISSUE THREAD

**Issue by wittend** [espressif/esptool#835]
### Operating System

Linux Mint 21 (Ubuntu)

### Esptool Version

v 4.4 

### Python Version

Python 3.10.6

### Full Esptool Command Line that Was Run

pip3 install --upgrade esptool  <also tried sudo>

### Esptool Output

```shell
NA - See attached file below.
```

### What is the Expected Behaviour?

Install esptool.py using pip.

### More Information

The problem seems to center on the package reedsolo.

[Pip3 esptool install error output.txt](https://github.com/espressif/esptool/files/10609688/Pip3.esptool.install.error.output.txt)

**Comment by dobairoland** [comment]
This is a duplicate of https://github.com/espressif/esptool/issues/829. Please see workaround there.

**Comment by wittend** [comment]
Thanks!  I didn't see that post.

Dave
