### ISSUE TITLE
Arm64 binary target (ESPTOOL-629)

### ISSUE THREAD

**Issue by JesseRiemens** [espressif/esptool#845]
### Is your feature request related to a problem?

There is no download for using ESPTOOL on a raspberry pi. This would be really useful in production programming for easy packaging of my app.

### Describe the solution you'd like

ARM64 added as build target in the pipeline

### Describe alternatives you've considered

I tried installing with pip, but that doesnt work with pyinstaller on my machine. I want to bundle the binary. 

I considered building myself however that is not maintainable.

**Comment by radimkarnis** [comment]
Hi @JesseRiemens,

Thanks for the feature request! Currently, GitHub Actions don't support arm64-based images on their runners. It would require a self-hosted runner to build esptool for raspberry pi. I will check if we can easily do this or not.

> I tried installing with pip, but that doesnt work with pyinstaller on my machine

Are there some issues with installing esptool with pip?
