### ISSUE TITLE
Add instructions for building the binary (ESPTOOL-640)

### ISSUE THREAD

**Issue by tnagorran** [espressif/esptool#854]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Add instructions to build the binary

### Describe alternatives you've considered

Create a script in the project to do so.

### Additional context

I can't figure out how you made the binary release.

**Comment by dobairoland** [comment]
You can find it [here](https://github.com/espressif/esptool/blob/master/.github/workflows/build_esptool.yml) how it is done.
