### ISSUE TITLE
A fatal error occurred: Invalid SLIP escape (0xdb, 0xF8)    无效的 SLIP 转义（0xdb、0xF8） (ESPTOOL-652)

### ISSUE THREAD

**Issue by 1158linzy** [espressif/esptool#863]
### Is your feature request related to a problem?

ESP8266，使用cmd命令行工具进行，写入、读取、擦除Flash时会出现这种问题？请大佬帮忙看看

**Comment by dobairoland** [comment]
See https://github.com/espressif/esptool/issues/862#issuecomment-1475758805
