### ISSUE TITLE
A fatal error occurred: Digest mismatch: expected 9968663DCF26F9F54857EC57C674092F, got BE642631C2501255F800D50A654843AB (ESPTOOL-654)

### ISSUE THREAD

**Issue by 1158linzy** [espressif/esptool#865]
### Is your feature request related to a problem?

ESP8266，使用cmd命令行工具进行，写入、读取、擦除Flash时会出现这种问题？请大佬帮忙看看

**Comment by dobairoland** [comment]
See https://github.com/espressif/esptool/issues/862#issuecomment-1475758805
