### ISSUE TITLE
Support reedsolo > 1.6 (ESPTOOL-668)

### ISSUE THREAD

**Issue by befeleme** [espressif/esptool#872]
### Is your feature request related to a problem?

Recently, there were two new versions of reedsolo released which contain some improvements to the package:
https://github.com/tomerfiliba-org/reedsolomon/releases
Could you support the latest version released (1.7.0) in esptool? Currently the versions are pinned: 

https://github.com/espressif/esptool/blob/53ae5eba4f968cfb49aefe8667e7d03a085ca1fa/setup.py#L128

### Describe the solution you'd like

Support the latest version of reedsolo released (1.7.0) 

### Additional context

The reason to update (or remove) the pin is because in Fedora Linux we already have the newest reedsolo and may need to patch our version of esptool downstream. It would be much better if the people who know how it's used in the codebase assessed it's safe to do so. Thank you.

**Comment by dobairoland** [comment]
- https://github.com/tomerfiliba-org/reedsolomon/releases/tag/v1.6.1 - this seems to be related to licenses only.
- https://github.com/tomerfiliba-org/reedsolomon/releases/tag/v1.7.0 - this is related to installation.

I think we can do as you suggest to easy dependency resolution. There should be no functional changes involved.
