### ISSUE TITLE
Support pyoxidizer by not using `__file__` (ESPTOOL-676)

### ISSUE THREAD

**Issue by maBarabas** [espressif/esptool#875]
### Is your feature request related to a problem?

An error is produced when using esptool under pyoxidizer. pyoxidizer does not define `__file__`, but esptool assumes that it is defined.

```
Traceback (most recent call last):
  File "runpy", line 196, in _run_module_as_main
  File "runpy", line 86, in _run_code
  File "main", line 1, in <module>
  File "esptool", line 42, in <module>
  File "esptool.cmds", line 14, in <module>
  File "esptool.bin_image", line 14, in <module>
  File "esptool.loader", line 78, in <module>
NameError: name '__file__' is not defined. Did you mean: '__name__'?
```

### Describe the solution you'd like

esptool should not assume that `__file__` is defined

### Describe alternatives you've considered

The [pyoxidizer docs](https://gregoryszorc.com/docs/pyoxidizer/stable/pyoxidizer_packaging_additional_files.html?highlight=__file__#installing-classified-resources-on-the-filesystem) offer a workaround that should work until this is fixed.

**Comment by peterdragun** [comment]
Hi, thank you for submitting the issue.
The reason for using the `__file__` is that we are trying to load non-python files such as flasher stub and we are trying to avoid using hardcoded paths. I have tried using some alternatives but none of them worked with in-memory libraries. From my understanding, there is a possibility to specify those resources in PyOxidizer to be also in memory but that would mean having paths hardcoded in esptool and then also the same paths in the config for PyOxidizer, which is not ideal. Personally, I don't have any experience with PyOxidizer and in-memory files like this, so maybe I am missing something. If you have a suggestion on how to fix this issue let us know or feel free to create a PR. Until then we would probably need to stick with a provided workaround.
