### ISSUE TITLE
running esptool.py -h fails (ESPTOOL-695)

### ISSUE THREAD

**Issue by rwblues** [espressif/esptool#887]
### Operating System

W 8.1

### Esptool Version

the latest version, download on 8 June 2023

### Python Version

3.7.3 py and 3.11.3

### Full Esptool Command Line that Was Run

py esptool.py -h

### Esptool Output

```shell
C:\Users\rwbdev\Desktop>py esptool.py -h
  File "C:\Users\rwbdev\Desktop\esptool.py", line 7
    <!DOCTYPE html>
    ^
 syntaxError: invalid syntax
```

### What is the Expected Behaviour?

disply help text on monitor

**Comment by radimkarnis** [comment]
Hi @rwblues,
you are probably trying to run some other file (maybe coincidentally also named `esptool.py`?)

The line `<!DOCTYPE html>` is not present anywhere in the esptool source code - and it's definitely not Python.

Try following the [installation instructions](https://docs.espressif.com/projects/esptool/en/latest/esp32/installation.html).
