### ISSUE TITLE
Failed to connect to ESP32 (ESPTOOL-711)

### ISSUE THREAD

**Issue by kevinTob1029** [espressif/esptool#897]
### Operating System

windows 10

### Esptool Version

v4.5.1

### Python Version

3.10.11

### Chip Description

ESP32-WROOM32

### Device Description

L298n Driver 

### Hardware Configuration

GPIO 14,27,26,25 are connected to L298n

### How is Esptool Run

Yes

### Full Esptool Command Line that Was Run

esptool.py COM8

### Esptool Output

```shell
esptool.py v4.5.1
Serial port COM8
Connecting......................................

A fatal error occurred: Failed to connect to ESP32: Invalid head of packet (0x00): Possible serial noise or corruption.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
the selected serial port For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
 does not exist or your board is not connected
```

### More Information

my L298n was on top of the esp32 while running, and i think the esp32 was short 

### Other Steps to Reproduce

no

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by dobairoland** [comment]
Please, if you think your device is broken then it makes no sense to report it as an esptool issue. Esptool cannot do anything with destroyed chips.

You can check your device by connecting to it by any terminal program and see if it send anything during boot. This is suggested in the troubleshooting guide: https://docs.espressif.com/projects/esptool/en/latest/esp32/troubleshooting.html#early-stage-crash
