### ISSUE TITLE
Cannot compile the ino code if Windows user contains whitespace with Arduino IDE (ESPTOOL-722)

### ISSUE THREAD

**Issue by icaksh** [espressif/esptool#905]
### Operating System

Windows 10

### Esptool Version

v4.5.1

### Python Version

Python 3.11

### Esptool Output

```shell
The file not readable
```

### More Information

Sorry if doesn't enough information about it because this problem happens like one or two weeks ago and I can't doing reproduce to make these issues.

These problems occur in my friend's PC (I try to solve it and not working) but when he tried on my PC (the username doesn't contain whitespace), it's working. After that I suspected that the error log contains the directory of Windows user ("C:\Users\Workload" "5\AppData\Arduino15...") and it says the file not readable. Seems that the path of directory is broken. The bug is only for esp32 because esptool for ESP8266 works fine without any problem.

It's working after my friend change the Windows username without any whitespace.

I want to pull requests but doesn't have the hardware and my Windows user doesn't contain whitespace.

### Other Steps to Reproduce

Add a new Windows user contains whitespace. Install Arduino as User-only (not global). After that try to compile example code in Arduino IDE and it will get an error.

**Comment by radimkarnis** [comment]
Hi @icaksh,

this doesn't seem like a problem with esptool but with the build system of Arduino core for esp32. Therefore, the issue should be opened in the [arduino-esp32](https://github.com/espressif/arduino-esp32) repository.

Also,  it is not easy to debug the issue without more information and a full log,

For these reasons, I am closing this ticket. Feel free to reopen if you believe it should be handled here.
