### ISSUE TITLE
The upload baud rate can't over 921600 (ESPTOOL-740)

### ISSUE THREAD

**Issue by Andy-Cheng1017** [espressif/esptool#919]
### Operating System

Ubuntu 22.04.3 LTS

### Esptool Version

esptool.py v4.6.2

### Python Version

Python 3.10.12

### Chip Description

ESP32-D0WD-V3 (revision v3.0)

### Device Description

ESP32-WROVER-IE-N16R8

### Hardware Configuration

![image](https://github.com/espressif/esptool/assets/73614623/77a9d42d-c651-43c9-aa74-2828b53a5660)

### How is Esptool Run

Terminal

### Full Esptool Command Line that Was Run

esptool.py -b 1152000 write_flash 0X10000 Pro-v1.0.16-202309151500_alpha.bin

### Esptool Output

```shell
andycheng@AndyLaptop:~/Nextcloud/Firmware/333ProFirmWare/TestingWriteFrom0X10000$ esptool.py -b 921600 write_flash 0X10000 Pro-v1.0.16-202309151500_alpha.bin
esptool.py v4.6.2
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting.....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting...
Detecting chip type... ESP32
Chip is ESP32-D0WD-V3 (revision v3.0)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 3c:61:05:4a:6b:04
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Flash will be erased from 0x00010000 to 0x001d4fff...
Compressed 1851472 bytes to 1063799...
Wrote 1851472 bytes (1063799 compressed) at 0x00010000 in 17.6 seconds (effective 841.2 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
andycheng@AndyLaptop:~/Nextcloud/Firmware/333ProFirmWare/TestingWriteFrom0X10000$ esptool.py -b 1152000 write_flash 0X10000 Pro-v1.0.16-202309151500_alpha.bin
esptool.py v4.6.2
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting...
Detecting chip type... ESP32
Chip is ESP32-D0WD-V3 (revision v3.0)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 3c:61:05:4a:6b:04
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 1152000
Changed.

A fatal error occurred: Unable to verify flash chip connection (No serial data received.).
```

### More Information

![image](https://github.com/espressif/esptool/assets/73614623/6627cc55-ff68-47f0-bd53-e87fa0b66ea1)

Before I using window esp flash tool the speed can reach to 1152000, I already check my USB chip cp2102 can reach 2Mb/s, I don't know why when I using esptool.py only can't over 921600

I already reduce my cable length to prevent the issues from cable, I think it's restricted from esptool  

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by radimkarnis** [comment]
Hello @Andy-Cheng1017,
esptool doesn't restrict the baud rate in any way. The support for higher baud rates is dependent on many factors, such as: host machine OS, USB drivers, pySerial version, USB-to-serial chip on the devkit, ...

Here is a log of me flashing an ESP32 with baudrate `1500000` on my Mac:

```
Stub running...
Changing baud rate to 1500000
Changed.
Configuring flash size...
Flash will be erased from 0x00000000 to 0x00000fff...
Compressed 200 bytes to 156...
Wrote 200 bytes (156 compressed) at 0x00000000 in 0.1 seconds (effective 19.7 kbit/s)...
Hash of data verified.
```
