### ISSUE TITLE
Issue with the serial monitor using ESP32-S3 and CH340G (ESPTOOL-763)

### ISSUE THREAD

**Issue by AlisonTristao** [espressif/esptool#930]
### Operating System

Ubuntu

### Esptool Version

esptool.py v4.5.1

### Python Version

Python 3.10.12

### Chip Description

Esp32-S3

### Device Description

User
I'm having trouble opening the serial monitor for the ESP32-S3. I'm developing my PCB with the ESP32-S3 and using the CH340G for automatic bootloader functionality. However, when I enter the serial monitor, my RST and CTS pins go LOW. 
When selecting the board as ESP32/ESP8266, the serial monitor opens perfectly

### Hardware Configuration

I'm connecting only the ESP's RX/TX pins to the CH340G, and the CTS and RTS pins to the EN and GPIO0 pins (I'm setting GPIO 46 and 45 to pull-down).

### How is Esptool Run

Arduino IDE and platformIO

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by dobairoland** [comment]
I'm sorry but this is esptool project which has nothing to do with the serial monitor of Arduino IDE. Beside that, we don't have the resources to deal with hardware issue. But at least I can recommend https://www.espressif.com/en/contact-us/circuit-schematic-pcb-design-review.
