### ISSUE TITLE
Reading flash from ESP32-S3 with read_flash command is very slow (ESPTOOL-774)

### ISSUE THREAD

**Issue by ciniml** [espressif/esptool#936]
### Operating System

Ubuntu 22.04

### Esptool Version

v4.7.dev3-5-gda4a486

### Python Version

Python 3.10.12

### Chip Description

ESP32-S3

### Device Description

ESP32-S3-WROOM-1-N8R8

### Hardware Configuration

Connect "USB" port (which is connected to internal USB Serial/JTAG) to host PC.
Force ESP32-S3 to enter download mode by pushing BOOT and RESET button on the board.

### How is Esptool Run

No IDE

### Full Esptool Command Line that Was Run

`esptool.py --port /dev/ttyACM1 --baud 1500000 read_flash 0 16777216 dump.bin`

### Esptool Output

```shell
$ esptool.py --port /dev/ttyACM1 --baud 1500000 read_flash 0 16777216 dump.bin
/home/kenta/.espressif/python_env/idf5.1_py3.10_env/bin/esptool.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('esptool==4.7.dev0', 'esptool.py')
esptool.py v4.7-dev
Serial port /dev/ttyACM1
Connecting...
Detecting chip type... ESP32-S3
Chip is ESP32-S3 (QFN56) (revision v0.1)
Features: WiFi, BLE, Embedded PSRAM 8MB (AP_3v3)
Crystal is 40MHz
MAC: 7c:df:a1:e0:98:b8
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 1500000
Changed.
16777216 (100 %)
16777216 (100 %)
Read 16777216 bytes at 0x00000000 in 2074.0 seconds (64.7 kbit/s)...
Hard resetting via RTS pin...
```

### More Information

The command takes around 15 minutes to complete. (around 8000 bytes/s to reading flash)

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by ciniml** [comment]
For some reason, the communication speed does not seem to change on the ESP32-S3 regardless of the --baud option setting.

With the same settings (only changing the read size to 4 [MiB]), I tried it on the ESP32-C3 and confirmed that the read speed changes with the `--baud` option setting.

**Comment by ciniml** [comment]
Through investigation, I confirmed that implementing the following measures improves the read speed to a normal level.

* Similar to flush timing in the USB-OTG driver, change it so that it only flushes when 64 bytes have accumulated or a 0xc0 transfer.
    * https://github.com/ciniml/esptool/blob/improve_esp32s3_read_flash_speed/flasher_stub/stub_io.c#L178
* When using the built-in USB Serial/JTAG, set the divider in uart_div_modify to 0.
    * https://github.com/ciniml/esptool/blob/improve_esp32s3_read_flash_speed/flasher_stub/stub_io.c#L309

**Comment by radimkarnis** [comment]
Hello @ciniml,
thank you for the report, thorough investigation, and a patch!

I can confirm this is a real issue and can be fully reproduced. We will fix this ASAP.

**Comment by ciniml** [comment]
Hello @radimkarnis .

I am testing the stub on Windows, but it seems that the transfer stops midway. It's likely that further adjustment of the flush timing is needed. I will continue to investigate what is happening.

**Comment by ciniml** [comment]
Hello. 

Further investigation has revealed that in the problematic Windows environment, reducing the accumulating amount from 64 bytes to 63 bytes prevents the system from hanging. 

The exact cause is not well understood, but when observing packet captures, it appears that packets of an unnaturally long length occur regularly with 64 bytes.
In the case of 63 bytes, such phenomena were not observed.

https://github.com/ciniml/esptool/tree/improve_esp32s3_read_flash_speed

<img width="1038" alt="image" src="https://github.com/espressif/esptool/assets/7610112/77f0b6b1-a95e-4f49-af3d-4859fa04582c">

<img width="1048" alt="image" src="https://github.com/espressif/esptool/assets/7610112/36a140aa-9e87-40b5-a1e4-f8743d21cf17">

**Comment by peterdragun** [comment]
Hi @ciniml, thank you for the investigation and providing the fix it is much appreciated. I have just one question.

> When using the built-in USB Serial/JTAG, set the divider in uart_div_modify to 0.
https://github.com/ciniml/esptool/blob/improve_esp32s3_read_flash_speed/flasher_stub/stub_io.c#L309

What is the issue with setting the divider? I have tried the fix with and without this part and I cannot see a difference. Can you please explain why you think this change is needed?

**Comment by g3gg0** [comment]
Am I reading it wrong, or do the commits say this should be fixed?
Doing some tests with [my own flash routines](https://github.com/g3gg0/esp32_flasher) and the [latest loaders](https://github.com/espressif/esptool/tree/master/esptool/targets/stub_flasher/1) show me this is still an issue.

```
       ESP32-C3
        [01:04:10] [DEBUG] ReadFlash timing: 262144 bytes in 22772ms
        [01:04:10] [DEBUG]   Data rate: 0.01 MB/s (11512 B/s)
        [01:04:10] [DEBUG]   Packet latency: min=348ms, max=358ms, avg=355.8ms
        [01:04:10] [DEBUG]   Packets received: 64
        
       ESP32-C6
        [01:05:00] [DEBUG] ReadFlash timing: 262144 bytes in 841ms
        [01:05:00] [DEBUG]   Data rate: 0.30 MB/s (311705 B/s)
        [01:05:00] [DEBUG]   Packet latency: min=13ms, max=14ms, avg=13.1ms
        [01:05:00] [DEBUG]   Packets received: 64

       ESP32-S3
        [01:06:29] [DEBUG] ReadFlash timing: 262144 bytes in 22762ms
        [01:06:29] [DEBUG]   Data rate: 0.01 MB/s (11517 B/s)
        [01:06:29] [DEBUG]   Packet latency: min=350ms, max=356ms, avg=355.6ms
        [01:06:29] [DEBUG]   Packets received: 64

```

**Comment by g3gg0** [comment]
Additionally, the [patch ](https://github.com/espressif/esptool-legacy-flasher-stub/commit/4e4de29e6082b06e190ec57c896ca71603554f56) which addresses this bug introduces a new feature.

The SLIP start marker (0xC0) which is the same as the end marker (0xC0) already causes a transmit on every first byte written to the buffer.
So any "single-transfer" kind of frame already triggers three bulk transfers on the USB-JTAG.
While is not a evil bug, it causes trouble with some [WebUSB implementation](https://www.g3gg0.de/programming/esp32-webserial-webusb-another-rabbit-hole/) i was trying to do.
@peterdragun

**Comment by Dzarda7** [comment]
I think the real issue here was that we were calling calling `stub_tx_flush` after each byte which was terribly inefficient. @ciniml improved this by flushing after 64 bytes, but considered the long packets an issue. I might be wrong, but I believe issue that happened was that there was no end of packet signalization when less than 64 bytes was sent as last transfer. Interesting that 63 works, there might be some timeout which considers 64 (max bulk transfer size) as special case and expects more data coming as if I am not wrong, proper way is to send zero length packet to signalize end of transaction when exactly 64 bytes was sent which I am not sure if is handled automatically. Will try to focus on fixing this properly in new [esp-flasher-stub](https://github.com/espressif/esp-flasher-stub).

**Comment by g3gg0** [comment]
just for record: fixed in [this PR](https://github.com/espressif/esptool-legacy-flasher-stub/pull/35) if someone wants to give it a try
