### ISSUE TITLE
esptool-v4.7.0-win64.zip is detected as Trojan:AndroidOS/ZkarletFlash by Windows Defender  (ESPTOOL-790)

### ISSUE THREAD

**Issue by rlowens** [espressif/esptool#944]
### Operating System

Windows 10

### Esptool Version

v4.7.0

### Python Version

N/A

### Esptool Output

```shell
Windows Defender (Security intelligence version: 1.403.1516.0 Version created on: 1/1/2024 9:21 PM) blocks access to esptool-v4.7.0-win64.zip as Trojan:AndroidOS/ZkarletFlash.

I've submitted the file for review at https://www.microsoft.com/en-us/wdsi/submission/67f5ca74-b772-4821-9730-ec0226f3d84c

If I manually Allow the detection in Windows Defender I can unzip and the resulting files are not detected as infected, only the zip file is.
```

### What is the Expected Behaviour?

File should download and be usable without Windows Defender blocking it.

### More Information

Detection by Windows Defender:
![esptool trojan scan](https://github.com/espressif/esptool/assets/35885181/9963cec1-72ce-45c1-be45-ba9ccd797c51)

Current online Windows Defender false-detection case result:
![image](https://github.com/espressif/esptool/assets/35885181/bd176ef6-ed35-4fe7-b81d-49eabf7a18f8)

I've also scanned esptool-v4.7.0-win64.zip with VirusTotal.com and it found 16 detections https://www.virustotal.com/gui/file/2bf76ac51f537f5e409fdc38e502f0ca4217db832af4572a80f97f2c6e1cb63e

![image](https://github.com/espressif/esptool/assets/35885181/24f76df5-1e1e-4a63-bb5d-ed02c23b4041)

Running the same Windows Defender and VirusTotal.com scans on esptool-v4.6.2-win64.zip result in no detections.

**Comment by Jason2866** [comment]
False positive virus alert. Caused from the used PyInstaller.

**Comment by radimkarnis** [comment]
Hello @rlowens,
thanks for the report and for submitting the file for review. This is indeed a false positive.

We sign the releases on Windows to prevent these false antivirus detections from happening, but that might not be enough.
I will also send the files for review, hopefully this will be whitelisted soon. 

I don't think there's more that can be done at the moment. I'll keep this open until the Microsoft ticket is resolved.
