### ISSUE TITLE
Complete Example Code - Had to add one extra text entry box in WiFi Credentials to get Password text to return and store in EEPROM (ESPTOOL-809)

### ISSUE THREAD

**Issue by 1-prop-head** [espressif/esptool#954]
### Operating System

Windows, Arduino

### Esptool Version

esptool 4.5.1

### Python Version

?

### Esptool Output

```shell
In general this is fantastic just a little tweek
```

### What is the Expected Behaviour?

Does not return wifi_pass_text in enterWiFiDetailsCallback 

### More Information

Pressing Save button String.println shows SSID but PWD was blank ten added a new text box in Credientials below password called extra and this then let the password text return work and save properly.
Also and this is not part of this problem but you may want to place a EEPROM.commit() just after the last EEPROM.write() and before the EEPROM.end() the close on the EEPROM write exit

### Other Steps to Reproduce

Adding a third text entry below the password fixed the issue.  Perhaps the last defined text entry element is not fully completed unless  another element is present below it.

**Comment by radimkarnis** [comment]
Hi @1-prop-head,

> In general this is fantastic just a little tweek

I am glad you are happy, but this is definitely the wrong place to open this ticket! This has nothing to do with esptool.py.

I guess you wanted to open this in the ESP32 Arduino Core repository, or maybe in a repo of some library.

I will close this issue on your behalf.
