### ISSUE TITLE
RUN only IPV6  (ESPTOOL-811)

### ISSUE THREAD

**Issue by ShubhadaHarkut-eaton** [espressif/esptool#956]
### Operating System

WINDOWS

### Esptool Version

4.4

### Python Version

3.8.7

### Chip Description

ESP32-WROVER-B

### Device Description

not able to disable the IPV4 
trying to use only IPV6

### How is Esptool Run

IDF IDE

### Esptool Output

```shell
Compilation errors with all IPV4 defines
```

### Other Steps to Reproduce

Build any ethernet example code disabling the LWIP_IPV4 in opts.h and enable the LWIP_IPV6 in the same file  

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by dobairoland** [comment]
This is not an esptool issue. Esptool flashes binaries and doesn't build them. You might want to report this for ESP-IDF or whatever other framework you are using for building the project.
